#!/bin/bash
# Save Claude Code conversation for later analysis
#
# This hook runs after each conversation ends.
# Conversations are saved to .claude/conversations/
#
# Environment variables available:
#   CLAUDE_CONVERSATION_ID - Unique ID for this conversation
#   CLAUDE_CONVERSATION_FILE - Path to conversation JSON (if available)
#   CLAUDE_SESSION_START - ISO timestamp when session started
#   CLAUDE_WORKING_DIR - Working directory

set -e

CONVERSATIONS_DIR="${CLAUDE_WORKING_DIR:-.}/.claude/conversations"
mkdir -p "$CONVERSATIONS_DIR"

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
CONVERSATION_ID="${CLAUDE_CONVERSATION_ID:-unknown}"

# Create conversation record
OUTPUT_FILE="$CONVERSATIONS_DIR/${TIMESTAMP}-${CONVERSATION_ID:0:8}.md"

{
  echo "# Conversation ${CONVERSATION_ID:0:8}"
  echo ""
  echo "- **Date**: $(date -Iseconds)"
  echo "- **Session Start**: ${CLAUDE_SESSION_START:-unknown}"
  echo "- **Working Directory**: ${CLAUDE_WORKING_DIR:-.}"
  echo "- **Conversation ID**: $CONVERSATION_ID"
  echo ""
  echo "---"
  echo ""
  echo "## Git Context"
  echo ""
  echo "\`\`\`"
  git -C "${CLAUDE_WORKING_DIR:-.}" log --oneline -5 2>/dev/null || echo "(not a git repo)"
  echo "\`\`\`"
  echo ""
  echo "## Modified Files (this session)"
  echo ""
  echo "\`\`\`"
  git -C "${CLAUDE_WORKING_DIR:-.}" status --short 2>/dev/null || echo "(not a git repo)"
  echo "\`\`\`"
  echo ""

  # If conversation file is available, include summary
  if [[ -n "$CLAUDE_CONVERSATION_FILE" && -f "$CLAUDE_CONVERSATION_FILE" ]]; then
    echo "## Conversation Data"
    echo ""
    echo "Full conversation saved at: \`$CLAUDE_CONVERSATION_FILE\`"
    echo ""
  fi

  echo "---"
  echo ""
  echo "*This file auto-generated by .claude/hooks/save-conversation.sh*"

} > "$OUTPUT_FILE"

echo "Conversation saved to $OUTPUT_FILE" >&2
