#!/bin/bash
# Save Claude Code conversation before compaction
#
# This hook runs before conversation compaction occurs, capturing the full
# uncompacted transcript for later analysis.
#
# Input (JSON via stdin):
#   session_id       - Unique session identifier
#   transcript_path  - Path to conversation JSONL file
#   trigger          - "manual" or "auto"
#
# Conversations are saved to .claude/conversations/

set -e

# Read JSON input from stdin
INPUT=$(cat)

SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // "unknown"')
TRANSCRIPT_PATH=$(echo "$INPUT" | jq -r '.transcript_path // ""')
TRIGGER=$(echo "$INPUT" | jq -r '.trigger // "unknown"')

# Get the project directory (where this script lives)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONVERSATIONS_DIR="${PROJECT_DIR}/conversations"

mkdir -p "$CONVERSATIONS_DIR"

TIMESTAMP=$(date +%Y%m%d-%H%M%S)

# Create conversation record
OUTPUT_FILE="$CONVERSATIONS_DIR/${TIMESTAMP}-${SESSION_ID:0:8}.md"
TRANSCRIPT_BACKUP="$CONVERSATIONS_DIR/${TIMESTAMP}-${SESSION_ID:0:8}.jsonl"

# Backup the full transcript before compaction
if [[ -n "$TRANSCRIPT_PATH" && -f "$TRANSCRIPT_PATH" ]]; then
  cp "$TRANSCRIPT_PATH" "$TRANSCRIPT_BACKUP"
fi

{
  echo "# Conversation ${SESSION_ID:0:8}"
  echo ""
  echo "- **Date**: $(date -Iseconds)"
  echo "- **Session ID**: $SESSION_ID"
  echo "- **Trigger**: $TRIGGER"
  echo "- **Working Directory**: $PROJECT_DIR"
  echo ""
  echo "---"
  echo ""
  echo "## Git Context"
  echo ""
  echo "\`\`\`"
  git -C "$PROJECT_DIR/.." log --oneline -5 2>/dev/null || echo "(not a git repo)"
  echo "\`\`\`"
  echo ""
  echo "## Modified Files (this session)"
  echo ""
  echo "\`\`\`"
  git -C "$PROJECT_DIR/.." status --short 2>/dev/null || echo "(not a git repo)"
  echo "\`\`\`"
  echo ""

  if [[ -f "$TRANSCRIPT_BACKUP" ]]; then
    echo "## Transcript"
    echo ""
    echo "Full conversation saved at: \`$TRANSCRIPT_BACKUP\`"
    echo ""
    # Count messages in transcript
    MSG_COUNT=$(wc -l < "$TRANSCRIPT_BACKUP" | tr -d ' ')
    echo "- Lines in transcript: $MSG_COUNT"
    echo ""
  fi

  echo "---"
  echo ""
  echo "*Auto-generated by .claude/hooks/save-conversation.sh (PreCompact hook)*"

} > "$OUTPUT_FILE"

echo "Conversation saved to $OUTPUT_FILE" >&2
