// Code generated by mcp-codegen from openapi.yaml. DO NOT EDIT.

package mcp

import "encoding/json"

// ServerInfo contains MCP server metadata
type ServerInfo struct {
	Name         string
	Version      string
	Instructions string
}

// GetServerInfo returns the MCP server metadata
func GetServerInfo() ServerInfo {
	return ServerInfo{
		Name:         "travel-calendar",
		Version:      "1.0.0",
		Instructions: "Travel Calendar MCP Server. Use these tools to manage trips, items, documents, location queries, and Google Calendar integration.\n\nKey tools:\n- get_trips: List and filter trips by upcoming/past/purpose\n- get_trip: Get detailed trip info including items and locations\n- create_trip: Create a new trip with optional default location\n- search_trips: Full-text search across trips\n- add_item: Add flights, hotels, trains, drives, or events to a trip\n- get_location_on_date: Find where the user will be on a specific date\n- get_location_range: Get location timeline for a date range\n- list_calendars: List available Google Calendars (requires OAuth)\n- get_calendar_conflicts: Detect conflicts between calendar events and trip locations\n- suggest_trips_from_calendar: Analyze calendar events to suggest potential trips\n\nAll dates use YYYY-MM-DD format. IDs are UUIDs.\n",
	}
}

// Resource represents an MCP resource
type Resource struct {
	URI         string
	Name        string
	Description string
	MimeType    string
}

// GetResources returns all MCP resources
func GetResources() []Resource {
	return []Resource{
	}
}

// Tool represents an MCP tool definition
type Tool struct {
	Name        string
	Description string
	InputSchema map[string]interface{}
}

// GetTools returns all MCP tool definitions
func GetTools() []Tool {
	return []Tool{
		{
			Name:        "add_item",
			Description: "Add an item to a trip. Type must be: flight, hotel, train, drive, or event. Fields vary by type - flights need from/to/carrier, hotels need name/location/checkIn/checkOut, etc.",
			InputSchema: parseSchema(`{
				"properties": {
					"carrier": {
						"type": "string"
					},
					"check_in": {
						"type": "string"
					},
					"check_out": {
						"type": "string"
					},
					"confirmation": {
						"type": "string"
					},
					"date": {
						"type": "string"
					},
					"flight_number": {
						"type": "string"
					},
					"from": {
						"type": "string"
					},
					"location": {
						"type": "string"
					},
					"name": {
						"type": "string"
					},
					"notes": {
						"type": "string"
					},
					"time": {
						"type": "string"
					},
					"to": {
						"type": "string"
					},
					"trip_id": {
						"description": "Trip ID",
						"type": "string"
					},
					"type": {
						"enum": [
							"flight",
							"hotel",
							"train",
							"drive",
							"event"
						],
						"type": "string"
					}
				},
				"required": [
					"trip_id",
					"type"
				],
				"type": "object"
			}`),
		},
		{
			Name:        "create_trip",
			Description: "Create a new trip. Required: name, purpose (business/vacation/conference/family/other). Optional: startDate, endDate (YYYY-MM-DD), status, notes, location (sets default location for all days).",
			InputSchema: parseSchema(`{
				"properties": {
					"end_date": {
						"type": "string"
					},
					"location": {
						"description": "Default location for all days of this trip (optional convenience)",
						"type": "string"
					},
					"name": {
						"type": "string"
					},
					"notes": {
						"type": "string"
					},
					"purpose": {
						"enum": [
							"business",
							"vacation",
							"conference",
							"family",
							"other"
						],
						"type": "string"
					},
					"start_date": {
						"type": "string"
					},
					"status": {
						"enum": [
							"planning",
							"confirmed",
							"in_progress",
							"completed",
							"cancelled"
						],
						"type": "string"
					}
				},
				"required": [
					"name",
					"purpose"
				],
				"type": "object"
			}`),
		},
		{
			Name:        "delete_item",
			Description: "Delete an item from a trip. This action cannot be undone.",
			InputSchema: parseSchema(`{
				"properties": {
					"item_id": {
						"description": "Item ID",
						"type": "string"
					}
				},
				"required": [
					"item_id"
				],
				"type": "object"
			}`),
		},
		{
			Name:        "delete_trip",
			Description: "Delete a trip and all its items. This action cannot be undone.",
			InputSchema: parseSchema(`{
				"properties": {
					"trip_id": {
						"description": "Trip ID",
						"type": "string"
					}
				},
				"required": [
					"trip_id"
				],
				"type": "object"
			}`),
		},
		{
			Name:        "get_base_locations",
			Description: "Get the user's configured base locations (home and work addresses). These are used as defaults when the user is not traveling.",
			InputSchema: parseSchema(`{
				"properties": {},
				"type": "object"
			}`),
		},
		{
			Name:        "get_calendar_conflicts",
			Description: "Detect calendar conflicts where events have locations that differ from the user's trip location on that date. Optionally filter by tripId or date range.",
			InputSchema: parseSchema(`{
				"properties": {
					"from": {
						"description": "Start date for range check (YYYY-MM-DD)",
						"type": "string"
					},
					"to": {
						"description": "End date for range check (YYYY-MM-DD)",
						"type": "string"
					},
					"trip_id": {
						"description": "Check conflicts for specific trip",
						"type": "string"
					}
				},
				"type": "object"
			}`),
		},
		{
			Name:        "get_documents",
			Description: "Get a list of documents. Filter by tripId to get documents for a specific trip, or use unassociated=true to get documents not linked to any trip.",
			InputSchema: parseSchema(`{
				"properties": {
					"trip_id": {
						"description": "Filter by trip ID",
						"type": "string"
					},
					"unassociated": {
						"description": "Return only documents not associated with a trip",
						"type": "boolean"
					}
				},
				"type": "object"
			}`),
		},
		{
			Name:        "get_location_on_date",
			Description: "Find out where the user will be on a specific date (YYYY-MM-DD). Returns the location(s) and source (home, work, or trip name).",
			InputSchema: parseSchema(`{
				"properties": {
					"date": {
						"description": "Date to query (YYYY-MM-DD)",
						"type": "string"
					}
				},
				"required": [
					"date"
				],
				"type": "object"
			}`),
		},
		{
			Name:        "get_location_range",
			Description: "Get a timeline of where the user will be across a date range. Returns location segments with dates and sources. Use from and to parameters (YYYY-MM-DD).",
			InputSchema: parseSchema(`{
				"properties": {
					"from": {
						"description": "Start date (YYYY-MM-DD)",
						"type": "string"
					},
					"to": {
						"description": "End date (YYYY-MM-DD)",
						"type": "string"
					}
				},
				"required": [
					"from",
					"to"
				],
				"type": "object"
			}`),
		},
		{
			Name:        "get_trip",
			Description: "Get detailed information about a specific trip including all its items (flights, hotels, etc.) and per-day locations.",
			InputSchema: parseSchema(`{
				"properties": {
					"trip_id": {
						"description": "Trip ID",
						"type": "string"
					}
				},
				"required": [
					"trip_id"
				],
				"type": "object"
			}`),
		},
		{
			Name:        "get_trip_locations",
			Description: "Get the per-day locations for a trip. Shows where the user will be on each day of the trip.",
			InputSchema: parseSchema(`{
				"properties": {
					"trip_id": {
						"description": "Trip ID",
						"type": "string"
					}
				},
				"required": [
					"trip_id"
				],
				"type": "object"
			}`),
		},
		{
			Name:        "get_trips",
			Description: "Get a list of trips. Filter by upcoming (future trips), past (completed trips), or purpose (business, vacation, conference, family, other).",
			InputSchema: parseSchema(`{
				"properties": {
					"past": {
						"description": "Filter to past trips only",
						"type": "boolean"
					},
					"purpose": {
						"description": "Filter by trip purpose",
						"enum": [
							"business",
							"vacation",
							"conference",
							"family",
							"other"
						],
						"type": "string"
					},
					"upcoming": {
						"description": "Filter to upcoming trips only",
						"type": "boolean"
					}
				},
				"type": "object"
			}`),
		},
		{
			Name:        "list_calendars",
			Description: "List all available Google Calendars for the authenticated user.",
			InputSchema: parseSchema(`{
				"properties": {},
				"type": "object"
			}`),
		},
		{
			Name:        "search_trips",
			Description: "Search trips by text. Searches across trip names, notes, and item details. Returns matching trips.",
			InputSchema: parseSchema(`{
				"properties": {
					"q": {
						"description": "Search query",
						"type": "string"
					}
				},
				"required": [
					"q"
				],
				"type": "object"
			}`),
		},
		{
			Name:        "set_base_locations",
			Description: "Set the user's base locations. Both home and work are optional. Example: home='New York, USA', work='Manhattan, NYC'.",
			InputSchema: parseSchema(`{
				"properties": {
					"home": {
						"type": "string"
					},
					"work": {
						"type": "string"
					}
				},
				"type": "object"
			}`),
		},
		{
			Name:        "set_trip_locations",
			Description: "Set locations for a trip. Use defaultLocation for a single location for all days, or locations array for per-day overrides. Dates use YYYY-MM-DD format.",
			InputSchema: parseSchema(`{
				"properties": {
					"default_location": {
						"description": "Default location for all dates not explicitly specified",
						"type": "string"
					},
					"locations": {
						"description": "Per-date location overrides",
						"items": {
							"properties": {
								"date": {
									"description": "The date (YYYY-MM-DD)",
									"type": "string"
								},
								"locations": {
									"description": "One or more locations for this date (multiple for travel days)",
									"items": {
										"type": "string"
									},
									"type": "array"
								}
							},
							"type": "object"
						},
						"type": "array"
					},
					"trip_id": {
						"description": "Trip ID",
						"type": "string"
					}
				},
				"required": [
					"trip_id"
				],
				"type": "object"
			}`),
		},
		{
			Name:        "suggest_trips_from_calendar",
			Description: "Analyze calendar events with locations to suggest potential trips. Returns events that appear to be travel-related based on location patterns.",
			InputSchema: parseSchema(`{
				"properties": {
					"from": {
						"description": "Start date (YYYY-MM-DD). Defaults to today.",
						"type": "string"
					},
					"to": {
						"description": "End date (YYYY-MM-DD). Defaults to 90 days from now.",
						"type": "string"
					}
				},
				"type": "object"
			}`),
		},
		{
			Name:        "update_trip",
			Description: "Update an existing trip. All fields are optional: name, purpose, startDate, endDate, status, notes.",
			InputSchema: parseSchema(`{
				"properties": {
					"end_date": {
						"type": "string"
					},
					"name": {
						"type": "string"
					},
					"notes": {
						"type": "string"
					},
					"purpose": {
						"enum": [
							"business",
							"vacation",
							"conference",
							"family",
							"other"
						],
						"type": "string"
					},
					"start_date": {
						"type": "string"
					},
					"status": {
						"enum": [
							"planning",
							"confirmed",
							"in_progress",
							"completed",
							"cancelled"
						],
						"type": "string"
					},
					"trip_id": {
						"description": "Trip ID",
						"type": "string"
					}
				},
				"required": [
					"trip_id"
				],
				"type": "object"
			}`),
		},
	}
}

// parseSchema parses a JSON schema string into a map
func parseSchema(s string) map[string]interface{} {
	var result map[string]interface{}
	if err := json.Unmarshal([]byte(s), &result); err != nil {
		panic("invalid schema: " + err.Error())
	}
	return result
}

// ToolNames returns a list of all tool names
func ToolNames() []string {
	tools := GetTools()
	names := make([]string, len(tools))
	for i, t := range tools {
		names[i] = t.Name
	}
	return names
}
