// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DocumentType.
const (
	DocumentTypeConfirmation DocumentType = "confirmation"
	DocumentTypeInsurance    DocumentType = "insurance"
	DocumentTypeItinerary    DocumentType = "itinerary"
	DocumentTypeOther        DocumentType = "other"
	DocumentTypePassport     DocumentType = "passport"
	DocumentTypeReceipt      DocumentType = "receipt"
	DocumentTypeVisa         DocumentType = "visa"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Defines values for ItemType.
const (
	Drive  ItemType = "drive"
	Event  ItemType = "event"
	Flight ItemType = "flight"
	Hotel  ItemType = "hotel"
	Train  ItemType = "train"
)

// Defines values for TripPurpose.
const (
	TripPurposeBusiness   TripPurpose = "business"
	TripPurposeConference TripPurpose = "conference"
	TripPurposeFamily     TripPurpose = "family"
	TripPurposeOther      TripPurpose = "other"
	TripPurposeVacation   TripPurpose = "vacation"
)

// Defines values for TripStatus.
const (
	Cancelled  TripStatus = "cancelled"
	Completed  TripStatus = "completed"
	Confirmed  TripStatus = "confirmed"
	InProgress TripStatus = "in_progress"
	Planning   TripStatus = "planning"
)

// CreateItemRequest defines model for CreateItemRequest.
type CreateItemRequest struct {
	Carrier      *string             `json:"carrier,omitempty"`
	CheckIn      *openapi_types.Date `json:"checkIn,omitempty"`
	CheckOut     *openapi_types.Date `json:"checkOut,omitempty"`
	Confirmation *string             `json:"confirmation,omitempty"`
	Date         *openapi_types.Date `json:"date,omitempty"`
	FlightNumber *string             `json:"flightNumber,omitempty"`
	From         *string             `json:"from,omitempty"`
	Location     *string             `json:"location,omitempty"`
	Name         *string             `json:"name,omitempty"`
	Notes        *string             `json:"notes,omitempty"`
	Time         *string             `json:"time,omitempty"`
	To           *string             `json:"to,omitempty"`
	Type         ItemType            `json:"type"`
}

// CreateTripRequest defines model for CreateTripRequest.
type CreateTripRequest struct {
	EndDate   *openapi_types.Date `json:"endDate,omitempty"`
	Name      string              `json:"name"`
	Notes     *string             `json:"notes,omitempty"`
	Purpose   TripPurpose         `json:"purpose"`
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
	Status    *TripStatus         `json:"status,omitempty"`
}

// Document defines model for Document.
type Document struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`

	// TripId Associated trip ID (null if unassociated)
	TripId    *openapi_types.UUID `json:"tripId,omitempty"`
	Type      DocumentType        `json:"type"`
	UpdatedAt time.Time           `json:"updatedAt"`

	// Url URL or file path to the document
	Url *string `json:"url,omitempty"`
}

// DocumentType defines model for Document.Type.
type DocumentType string

// Error defines model for Error.
type Error struct {
	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error message
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Service string               `json:"service"`
	Status  HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// Item defines model for Item.
type Item struct {
	// Carrier Airline or train operator
	Carrier      *string             `json:"carrier,omitempty"`
	CheckIn      *openapi_types.Date `json:"checkIn,omitempty"`
	CheckOut     *openapi_types.Date `json:"checkOut,omitempty"`
	Confirmation *string             `json:"confirmation,omitempty"`
	CreatedAt    time.Time           `json:"createdAt"`
	Date         *openapi_types.Date `json:"date,omitempty"`
	FlightNumber *string             `json:"flightNumber,omitempty"`

	// From Origin location or airport code
	From     *string            `json:"from,omitempty"`
	Id       openapi_types.UUID `json:"id"`
	Location *string            `json:"location,omitempty"`

	// Name Hotel or event name
	Name  *string `json:"name,omitempty"`
	Notes *string `json:"notes,omitempty"`

	// Time Time in HH:MM format
	Time *string `json:"time,omitempty"`

	// To Destination location or airport code
	To        *string            `json:"to,omitempty"`
	TripId    openapi_types.UUID `json:"tripId"`
	Type      ItemType           `json:"type"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// ItemType defines model for ItemType.
type ItemType string

// Trip defines model for Trip.
type Trip struct {
	CreatedAt time.Time `json:"createdAt"`

	// EndDate Trip end date (YYYY-MM-DD)
	EndDate *openapi_types.Date `json:"endDate,omitempty"`
	Id      openapi_types.UUID  `json:"id"`

	// Items Trip items (only included when fetching a single trip)
	Items   *[]Item     `json:"items,omitempty"`
	Name    string      `json:"name"`
	Notes   *string     `json:"notes,omitempty"`
	Purpose TripPurpose `json:"purpose"`

	// StartDate Trip start date (YYYY-MM-DD)
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
	Status    TripStatus          `json:"status"`
	UpdatedAt time.Time           `json:"updatedAt"`
}

// TripPurpose defines model for TripPurpose.
type TripPurpose string

// TripStatus defines model for TripStatus.
type TripStatus string

// UpdateTripRequest defines model for UpdateTripRequest.
type UpdateTripRequest struct {
	EndDate   *openapi_types.Date `json:"endDate,omitempty"`
	Name      *string             `json:"name,omitempty"`
	Notes     *string             `json:"notes,omitempty"`
	Purpose   *TripPurpose        `json:"purpose,omitempty"`
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
	Status    *TripStatus         `json:"status,omitempty"`
}

// ItemId defines model for ItemId.
type ItemId = openapi_types.UUID

// TripId defines model for TripId.
type TripId = openapi_types.UUID

// ListDocumentsParams defines parameters for ListDocuments.
type ListDocumentsParams struct {
	// TripId Filter by trip ID
	TripId *openapi_types.UUID `form:"tripId,omitempty" json:"tripId,omitempty"`

	// Unassociated Return only documents not associated with a trip
	Unassociated *bool `form:"unassociated,omitempty" json:"unassociated,omitempty"`
}

// ListTripsParams defines parameters for ListTrips.
type ListTripsParams struct {
	// Upcoming Filter to upcoming trips only
	Upcoming *bool `form:"upcoming,omitempty" json:"upcoming,omitempty"`

	// Past Filter to past trips only
	Past *bool `form:"past,omitempty" json:"past,omitempty"`

	// Purpose Filter by trip purpose
	Purpose *TripPurpose `form:"purpose,omitempty" json:"purpose,omitempty"`
}

// SearchTripsParams defines parameters for SearchTrips.
type SearchTripsParams struct {
	// Q Search query
	Q string `form:"q" json:"q"`
}

// CreateTripJSONRequestBody defines body for CreateTrip for application/json ContentType.
type CreateTripJSONRequestBody = CreateTripRequest

// UpdateTripJSONRequestBody defines body for UpdateTrip for application/json ContentType.
type UpdateTripJSONRequestBody = UpdateTripRequest

// CreateTripItemJSONRequestBody defines body for CreateTripItem for application/json ContentType.
type CreateTripItemJSONRequestBody = CreateItemRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List documents
	// (GET /api/documents)
	ListDocuments(w http.ResponseWriter, r *http.Request, params ListDocumentsParams)
	// Delete an item
	// (DELETE /api/items/{itemId})
	DeleteItem(w http.ResponseWriter, r *http.Request, itemId ItemId)
	// List trips
	// (GET /api/trips)
	ListTrips(w http.ResponseWriter, r *http.Request, params ListTripsParams)
	// Create a new trip
	// (POST /api/trips)
	CreateTrip(w http.ResponseWriter, r *http.Request)
	// Search trips
	// (GET /api/trips/search)
	SearchTrips(w http.ResponseWriter, r *http.Request, params SearchTripsParams)
	// Delete a trip
	// (DELETE /api/trips/{tripId})
	DeleteTrip(w http.ResponseWriter, r *http.Request, tripId TripId)
	// Get a trip by ID
	// (GET /api/trips/{tripId})
	GetTrip(w http.ResponseWriter, r *http.Request, tripId TripId)
	// Update a trip
	// (PATCH /api/trips/{tripId})
	UpdateTrip(w http.ResponseWriter, r *http.Request, tripId TripId)
	// List items for a trip
	// (GET /api/trips/{tripId}/items)
	ListTripItems(w http.ResponseWriter, r *http.Request, tripId TripId)
	// Add an item to a trip
	// (POST /api/trips/{tripId}/items)
	CreateTripItem(w http.ResponseWriter, r *http.Request, tripId TripId)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List documents
// (GET /api/documents)
func (_ Unimplemented) ListDocuments(w http.ResponseWriter, r *http.Request, params ListDocumentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an item
// (DELETE /api/items/{itemId})
func (_ Unimplemented) DeleteItem(w http.ResponseWriter, r *http.Request, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List trips
// (GET /api/trips)
func (_ Unimplemented) ListTrips(w http.ResponseWriter, r *http.Request, params ListTripsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new trip
// (POST /api/trips)
func (_ Unimplemented) CreateTrip(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search trips
// (GET /api/trips/search)
func (_ Unimplemented) SearchTrips(w http.ResponseWriter, r *http.Request, params SearchTripsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a trip
// (DELETE /api/trips/{tripId})
func (_ Unimplemented) DeleteTrip(w http.ResponseWriter, r *http.Request, tripId TripId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a trip by ID
// (GET /api/trips/{tripId})
func (_ Unimplemented) GetTrip(w http.ResponseWriter, r *http.Request, tripId TripId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a trip
// (PATCH /api/trips/{tripId})
func (_ Unimplemented) UpdateTrip(w http.ResponseWriter, r *http.Request, tripId TripId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List items for a trip
// (GET /api/trips/{tripId}/items)
func (_ Unimplemented) ListTripItems(w http.ResponseWriter, r *http.Request, tripId TripId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add an item to a trip
// (POST /api/trips/{tripId}/items)
func (_ Unimplemented) CreateTripItem(w http.ResponseWriter, r *http.Request, tripId TripId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDocuments operation middleware
func (siw *ServerInterfaceWrapper) ListDocuments(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDocumentsParams

	// ------------- Optional query parameter "tripId" -------------

	err = runtime.BindQueryParameter("form", true, false, "tripId", r.URL.Query(), &params.TripId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Optional query parameter "unassociated" -------------

	err = runtime.BindQueryParameter("form", true, false, "unassociated", r.URL.Query(), &params.Unassociated)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "unassociated", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDocuments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTrips operation middleware
func (siw *ServerInterfaceWrapper) ListTrips(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTripsParams

	// ------------- Optional query parameter "upcoming" -------------

	err = runtime.BindQueryParameter("form", true, false, "upcoming", r.URL.Query(), &params.Upcoming)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "upcoming", Err: err})
		return
	}

	// ------------- Optional query parameter "past" -------------

	err = runtime.BindQueryParameter("form", true, false, "past", r.URL.Query(), &params.Past)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "past", Err: err})
		return
	}

	// ------------- Optional query parameter "purpose" -------------

	err = runtime.BindQueryParameter("form", true, false, "purpose", r.URL.Query(), &params.Purpose)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "purpose", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTrips(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTrip operation middleware
func (siw *ServerInterfaceWrapper) CreateTrip(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTrip(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchTrips operation middleware
func (siw *ServerInterfaceWrapper) SearchTrips(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchTripsParams

	// ------------- Required query parameter "q" -------------

	if paramValue := r.URL.Query().Get("q"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchTrips(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTrip operation middleware
func (siw *ServerInterfaceWrapper) DeleteTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId TripId

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrip operation middleware
func (siw *ServerInterfaceWrapper) GetTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId TripId

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTrip operation middleware
func (siw *ServerInterfaceWrapper) UpdateTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId TripId

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTripItems operation middleware
func (siw *ServerInterfaceWrapper) ListTripItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId TripId

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTripItems(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTripItem operation middleware
func (siw *ServerInterfaceWrapper) CreateTripItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId TripId

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTripItem(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/documents", wrapper.ListDocuments)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/items/{itemId}", wrapper.DeleteItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/trips", wrapper.ListTrips)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/trips", wrapper.CreateTrip)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/trips/search", wrapper.SearchTrips)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/trips/{tripId}", wrapper.DeleteTrip)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/trips/{tripId}", wrapper.GetTrip)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/trips/{tripId}", wrapper.UpdateTrip)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/trips/{tripId}/items", wrapper.ListTripItems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/trips/{tripId}/items", wrapper.CreateTripItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})

	return r
}
