/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the service
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List trips
         * @description Returns a list of trips, optionally filtered
         */
        get: operations["listTrips"];
        put?: never;
        /** Create a new trip */
        post: operations["createTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search trips
         * @description Full-text search across trip names, notes, and items
         */
        get: operations["searchTrips"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a trip by ID */
        get: operations["getTrip"];
        put?: never;
        post?: never;
        /** Delete a trip */
        delete: operations["deleteTrip"];
        options?: never;
        head?: never;
        /** Update a trip */
        patch: operations["updateTrip"];
        trace?: never;
    };
    "/api/trips/{tripId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List items for a trip */
        get: operations["listTripItems"];
        put?: never;
        /** Add an item to a trip */
        post: operations["createTripItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an item */
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents */
        get: operations["listDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            service: string;
        };
        /** @enum {string} */
        TripPurpose: "business" | "vacation" | "conference" | "family" | "other";
        /** @enum {string} */
        TripStatus: "planning" | "confirmed" | "in_progress" | "completed" | "cancelled";
        Trip: {
            /** Format: uuid */
            id: string;
            name: string;
            purpose: components["schemas"]["TripPurpose"];
            /**
             * Format: date
             * @description Trip start date (YYYY-MM-DD)
             */
            startDate?: string;
            /**
             * Format: date
             * @description Trip end date (YYYY-MM-DD)
             */
            endDate?: string;
            status: components["schemas"]["TripStatus"];
            notes?: string;
            /** @description Trip items (only included when fetching a single trip) */
            items?: components["schemas"]["Item"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateTripRequest: {
            name: string;
            purpose: components["schemas"]["TripPurpose"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** @default planning */
            status: components["schemas"]["TripStatus"];
            notes?: string;
        };
        UpdateTripRequest: {
            name?: string;
            purpose?: components["schemas"]["TripPurpose"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            status?: components["schemas"]["TripStatus"];
            notes?: string;
        };
        /** @enum {string} */
        ItemType: "flight" | "hotel" | "train" | "drive" | "event";
        Item: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tripId: string;
            type: components["schemas"]["ItemType"];
            /** Format: date */
            date?: string;
            /** @description Time in HH:MM format */
            time?: string;
            confirmation?: string;
            notes?: string;
            /** @description Origin location or airport code */
            from?: string;
            /** @description Destination location or airport code */
            to?: string;
            /** @description Airline or train operator */
            carrier?: string;
            flightNumber?: string;
            /** @description Hotel or event name */
            name?: string;
            location?: string;
            /** Format: date */
            checkIn?: string;
            /** Format: date */
            checkOut?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateItemRequest: {
            type: components["schemas"]["ItemType"];
            /** Format: date */
            date?: string;
            time?: string;
            confirmation?: string;
            notes?: string;
            from?: string;
            to?: string;
            carrier?: string;
            flightNumber?: string;
            name?: string;
            location?: string;
            /** Format: date */
            checkIn?: string;
            /** Format: date */
            checkOut?: string;
        };
        Document: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Associated trip ID (null if unassociated)
             */
            tripId?: string;
            name: string;
            /** @enum {string} */
            type: "confirmation" | "itinerary" | "receipt" | "visa" | "passport" | "insurance" | "other";
            /**
             * Format: uri
             * @description URL or file path to the document
             */
            url?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Error: {
            /** @description Error message */
            error: string;
            /** @description Additional error details */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: {
        /** @description Trip ID */
        TripId: string;
        /** @description Item ID */
        ItemId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "service": "backend"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTrips: {
        parameters: {
            query?: {
                /** @description Filter to upcoming trips only */
                upcoming?: boolean;
                /** @description Filter to past trips only */
                past?: boolean;
                /** @description Filter by trip purpose */
                purpose?: components["schemas"]["TripPurpose"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of trips */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"][];
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "FOSDEM 2025",
                 *       "purpose": "conference",
                 *       "startDate": "2025-01-29",
                 *       "endDate": "2025-02-02",
                 *       "notes": "Annual open source conference in Brussels"
                 *     }
                 */
                "application/json": components["schemas"]["CreateTripRequest"];
            };
        };
        responses: {
            /** @description Trip created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    searchTrips: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"][];
                };
            };
            /** @description Invalid search query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTripRequest"];
            };
        };
        responses: {
            /** @description Trip updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTripItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"][];
                };
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createTripItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemRequest"];
            };
        };
        responses: {
            /** @description Item created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                /** @description Filter by trip ID */
                tripId?: string;
                /** @description Return only documents not associated with a trip */
                unassociated?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
