/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the service
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List trips
         * @description Returns a list of trips, optionally filtered
         */
        get: operations["listTrips"];
        put?: never;
        /** Create a new trip */
        post: operations["createTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search trips
         * @description Full-text search across trip names, notes, and items
         */
        get: operations["searchTrips"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a trip by ID */
        get: operations["getTrip"];
        put?: never;
        post?: never;
        /** Delete a trip */
        delete: operations["deleteTrip"];
        options?: never;
        head?: never;
        /** Update a trip */
        patch: operations["updateTrip"];
        trace?: never;
    };
    "/api/trips/{sourceId}/merge/{targetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge one trip into another
         * @description Merges the source trip into the target trip:
         *     - All items from source are moved to target
         *     - Target dates extended if source dates are outside range
         *     - Notes concatenated (target + source) if mergeNotes is true
         *     - Source trip deleted after merge if deleteSource is true
         */
        post: operations["mergeTrips"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List items for a trip */
        get: operations["listTripItems"];
        put?: never;
        /** Add an item to a trip */
        post: operations["createTripItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an item */
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{itemId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move an item to another trip
         * @description Moves an item to a different trip. Can either:
         *     - Move to an existing trip (provide targetTripId)
         *     - Create a new trip and move item to it (provide newTrip)
         */
        post: operations["moveItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents */
        get: operations["listDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get base locations
         * @description Returns the user's configured base locations (home, work)
         */
        get: operations["getBaseLocations"];
        /**
         * Set base locations
         * @description Configure the user's base locations (home, work)
         */
        put: operations["setBaseLocations"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get locations for a trip
         * @description Returns per-date location data for a trip
         */
        get: operations["getTripLocations"];
        /**
         * Set locations for a trip
         * @description Set per-date locations for a trip. Replaces existing location data.
         */
        put: operations["setTripLocations"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/location/on/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user location on a specific date
         * @description Returns where the user will be on a specific date.
         *     - If the date falls within a trip with explicit location, returns that location
         *     - If the date falls within a trip without explicit location, returns "Away"
         *     - If not within any trip, returns the user's home location
         */
        get: operations["getLocationOnDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/location/range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user locations for a date range
         * @description Returns a timeline of where the user will be across a date range.
         *     Consecutive days at the same location are grouped into segments.
         */
        get: operations["getLocationRange"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Google OAuth URL
         * @description Returns the URL to redirect the user for Google OAuth authorization
         */
        get: operations["getGoogleAuthUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Handle Google OAuth callback
         * @description Exchanges authorization code for tokens and stores credentials. Redirects to settings page.
         */
        get: operations["handleGoogleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Google authentication status
         * @description Returns whether Google Calendar is connected and which scopes are authorized
         */
        get: operations["getGoogleAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disconnect Google Calendar
         * @description Revokes access and deletes stored credentials
         */
        post: operations["disconnectGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available Google Calendars
         * @description Returns all calendars from the user's Google account
         */
        get: operations["listCalendars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendars/selected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get selected calendars
         * @description Returns calendars the user has selected to monitor
         */
        get: operations["getSelectedCalendars"];
        /**
         * Set selected calendars
         * @description Updates which calendars to monitor for conflicts and suggestions
         */
        put: operations["setSelectedCalendars"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List calendar events
         * @description Returns events from selected calendars within date range
         */
        get: operations["listCalendarEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detect calendar conflicts with trips
         * @description Returns events where the event location differs from the user's trip location on that date
         */
        get: operations["getCalendarConflicts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar/trip-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggest trips from calendar events
         * @description Analyzes calendar events with locations to suggest potential trips
         */
        get: operations["suggestTripsFromCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar/trip-suggestions/{suggestionId}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a trip suggestion
         * @description Creates a trip from a calendar-based suggestion
         */
        post: operations["importTripSuggestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar/trip-suggestions/{suggestionId}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss a trip suggestion
         * @description Marks a trip suggestion as dismissed so it won't appear again
         */
        post: operations["dismissTripSuggestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar/trip-suggestions/{suggestionId}/merge/{tripId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge a trip suggestion into an existing trip
         * @description Adds items from the suggestion to an existing trip and extends dates if needed
         */
        post: operations["mergeTripSuggestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar/processed-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Reset all processed calendar events
         * @description Clears the record of processed events, allowing dismissed suggestions to reappear
         */
        delete: operations["resetProcessedEvents"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/calendar-sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get calendar links for a trip
         * @description Returns existing calendar event links for this trip
         */
        get: operations["getTripCalendarLinks"];
        put?: never;
        /**
         * Sync trip to Google Calendar
         * @description Creates or updates calendar events for trip and its items
         */
        post: operations["syncTripToCalendar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            service: string;
        };
        /** @enum {string} */
        TripPurpose: "business" | "vacation" | "conference" | "family" | "other";
        /** @enum {string} */
        TripStatus: "planning" | "confirmed" | "in_progress" | "completed" | "cancelled";
        Trip: {
            /** Format: uuid */
            id: string;
            name: string;
            purpose: components["schemas"]["TripPurpose"];
            /**
             * Format: date
             * @description Trip start date (YYYY-MM-DD)
             */
            startDate?: string;
            /**
             * Format: date
             * @description Trip end date (YYYY-MM-DD)
             */
            endDate?: string;
            status: components["schemas"]["TripStatus"];
            notes?: string;
            /** @description Trip items (only included when fetching a single trip) */
            items?: components["schemas"]["Item"][];
            /** @description Per-date locations for this trip (only included when fetching a single trip) */
            locations?: components["schemas"]["TripDayLocation"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateTripRequest: {
            name: string;
            purpose: components["schemas"]["TripPurpose"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** @default planning */
            status: components["schemas"]["TripStatus"];
            notes?: string;
            /** @description Default location for all days of this trip (optional convenience) */
            location?: string;
        };
        UpdateTripRequest: {
            name?: string;
            purpose?: components["schemas"]["TripPurpose"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            status?: components["schemas"]["TripStatus"];
            notes?: string;
        };
        /** @enum {string} */
        ItemType: "flight" | "hotel" | "train" | "drive" | "event";
        Item: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tripId: string;
            type: components["schemas"]["ItemType"];
            /** Format: date */
            date?: string;
            /** @description Time in HH:MM format */
            time?: string;
            confirmation?: string;
            notes?: string;
            /** @description Origin location or airport code */
            from?: string;
            /** @description Destination location or airport code */
            to?: string;
            /** @description Airline or train operator */
            carrier?: string;
            flightNumber?: string;
            /** @description Hotel or event name */
            name?: string;
            location?: string;
            /** Format: date */
            checkIn?: string;
            /** Format: date */
            checkOut?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateItemRequest: {
            type: components["schemas"]["ItemType"];
            /** Format: date */
            date?: string;
            time?: string;
            confirmation?: string;
            notes?: string;
            from?: string;
            to?: string;
            carrier?: string;
            flightNumber?: string;
            name?: string;
            location?: string;
            /** Format: date */
            checkIn?: string;
            /** Format: date */
            checkOut?: string;
        };
        Document: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Associated trip ID (null if unassociated)
             */
            tripId?: string;
            name: string;
            /** @enum {string} */
            type: "confirmation" | "itinerary" | "receipt" | "visa" | "passport" | "insurance" | "other";
            /**
             * Format: uri
             * @description URL or file path to the document
             */
            url?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Error: {
            /** @description Error message */
            error: string;
            /** @description Additional error details */
            details?: {
                [key: string]: unknown;
            };
        };
        BaseLocations: {
            /** @description Home location (default "Home" if not configured) */
            home?: string;
            /** @description Work location (optional) */
            work?: string;
        };
        SetBaseLocationsRequest: {
            home?: string;
            work?: string;
        };
        TripDayLocation: {
            /**
             * Format: date
             * @description The date (YYYY-MM-DD)
             */
            date: string;
            /** @description One or more locations for this date (multiple for travel days) */
            locations: string[];
        };
        SetTripLocationsRequest: {
            /** @description Default location for all dates not explicitly specified */
            defaultLocation?: string;
            /** @description Per-date location overrides */
            locations?: components["schemas"]["TripDayLocation"][];
        };
        /**
         * @description The source of the location (home, work, or a trip)
         * @enum {string}
         */
        LocationSourceType: "home" | "work" | "trip";
        LocationSource: {
            type: components["schemas"]["LocationSourceType"];
            /**
             * Format: uuid
             * @description Present when type is "trip"
             */
            tripId?: string;
            /** @description Present when type is "trip" */
            tripName?: string;
        };
        LocationOnDateResponse: {
            /** Format: date */
            date: string;
            /** @description Location(s) on this date */
            locations: string[];
            source: components["schemas"]["LocationSource"];
        };
        LocationRangeSegment: {
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** @description Location(s) for this segment */
            locations: string[];
            source: components["schemas"]["LocationSource"];
        };
        OAuthUrlResponse: {
            /**
             * Format: uri
             * @description OAuth authorization URL to redirect the user to
             */
            url: string;
        };
        GoogleAuthStatus: {
            /** @description Whether Google Calendar is connected */
            connected: boolean;
            /**
             * Format: email
             * @description Connected Google account email
             */
            email?: string;
            /** @description Authorized OAuth scopes */
            scopes?: string[];
            /**
             * Format: date-time
             * @description When the access token expires
             */
            expiresAt?: string;
        };
        GoogleCalendar: {
            /** @description Google Calendar ID */
            id: string;
            /** @description Calendar display name */
            name: string;
            /** @description Calendar description */
            description?: string;
            /** @description Whether this is the user's primary calendar */
            primary?: boolean;
            /** @description Calendar color (hex code) */
            backgroundColor?: string;
            /**
             * @description User's access level to this calendar
             * @enum {string}
             */
            accessRole?: "owner" | "writer" | "reader" | "freeBusyReader";
        };
        UserCalendar: {
            /** @description Google Calendar ID */
            calendarId: string;
            /** @description Calendar display name */
            name: string;
            /** @description Whether this calendar is enabled for monitoring */
            enabled: boolean;
        };
        SetSelectedCalendarsRequest: {
            /** @description List of calendar IDs to enable for monitoring */
            calendarIds: string[];
        };
        CalendarEvent: {
            /** @description Google Calendar event ID */
            id: string;
            /** @description Calendar this event belongs to */
            calendarId: string;
            /** @description Event title */
            summary: string;
            /** @description Event description */
            description?: string;
            /** @description Event location */
            location?: string;
            /**
             * Format: date-time
             * @description Event start time
             */
            start: string;
            /**
             * Format: date-time
             * @description Event end time
             */
            end: string;
            /** @description Whether this is an all-day event */
            allDay?: boolean;
            /**
             * Format: uri
             * @description Link to view event in Google Calendar
             */
            htmlLink?: string;
        };
        CalendarConflict: {
            event: components["schemas"]["CalendarEvent"];
            /** @description Location of the calendar event */
            eventLocation: string;
            /** @description Where the user will actually be (from trip) */
            userLocation: string;
            /**
             * Format: date
             * @description Date of the conflict
             */
            date: string;
            /**
             * Format: uuid
             * @description ID of the trip causing the conflict
             */
            tripId?: string;
            /** @description Name of the trip causing the conflict */
            tripName?: string;
        };
        TripSuggestion: {
            /** @description Unique ID for this suggestion (for import) */
            id: string;
            /** @description Suggested trip name */
            name: string;
            /**
             * Format: date
             * @description Suggested start date
             */
            startDate: string;
            /**
             * Format: date
             * @description Suggested end date
             */
            endDate: string;
            /** @description Suggested destination */
            location: string;
            purpose?: components["schemas"]["TripPurpose"];
            /** @description Calendar events that led to this suggestion */
            sourceEvents: components["schemas"]["CalendarEvent"][];
            /**
             * @description Source of the suggestion (google calendar or tripit)
             * @enum {string}
             */
            source?: "google" | "tripit";
            /** @description Items parsed from source events (flights, hotels, events) */
            suggestedItems?: components["schemas"]["SuggestedItem"][];
            /** @description Existing trips that could be merged with this suggestion */
            mergeCandidates?: components["schemas"]["MergeCandidate"][];
        };
        SuggestedItem: {
            type: components["schemas"]["ItemType"];
            /** @description Source calendar event ID */
            calendarEventId: string;
            /** Format: date */
            date?: string;
            time?: string;
            from?: string;
            to?: string;
            carrier?: string;
            flightNumber?: string;
            name?: string;
            location?: string;
            confirmation?: string;
            notes?: string;
        };
        MergeCandidate: {
            /** Format: uuid */
            tripId: string;
            tripName: string;
            /** @description Why this trip matches (e.g., "Same location, overlapping dates") */
            matchReason: string;
        };
        SyncTripRequest: {
            /** @description Which calendar to sync to (defaults to primary) */
            targetCalendarId?: string;
            /**
             * @description Whether to create new events
             * @default true
             */
            createEvents: boolean;
            /**
             * @description Whether to include flight items
             * @default true
             */
            includeFlights: boolean;
            /**
             * @description Whether to include hotel items
             * @default true
             */
            includeHotels: boolean;
            /**
             * @description Whether to include event items
             * @default true
             */
            includeEvents: boolean;
        };
        SyncTripResult: {
            /** @description Number of new events created */
            eventsCreated: number;
            /** @description Number of existing events updated */
            eventsUpdated: number;
            /** @description Links between trip items and calendar events */
            calendarLinks?: components["schemas"]["CalendarLink"][];
        };
        CalendarLink: {
            /**
             * Format: uuid
             * @description Trip ID
             */
            tripId: string;
            /**
             * Format: uuid
             * @description Item ID (if linked to a specific item)
             */
            itemId?: string;
            /** @description Google Calendar ID */
            calendarId: string;
            /** @description Google Calendar event ID */
            eventId: string;
            /**
             * Format: date-time
             * @description When this link was last synced
             */
            syncedAt: string;
            /**
             * Format: uri
             * @description Link to view event in Google Calendar
             */
            htmlLink?: string;
        };
        MergeTripsRequest: {
            /**
             * @description Whether to delete the source trip after merge
             * @default true
             */
            deleteSource: boolean;
            /**
             * @description Whether to concatenate notes from both trips
             * @default true
             */
            mergeNotes: boolean;
        };
        MoveItemRequest: {
            /**
             * Format: uuid
             * @description ID of existing trip to move item to
             */
            targetTripId?: string;
            /** @description Details for creating a new trip (if not moving to existing) */
            newTrip?: components["schemas"]["CreateTripRequest"];
        };
        MoveItemResponse: {
            /** @description The moved item with updated tripId */
            item: components["schemas"]["Item"];
            /** @description The target trip (included if newTrip was created) */
            trip?: components["schemas"]["Trip"];
        };
    };
    responses: never;
    parameters: {
        /** @description Trip ID */
        TripId: string;
        /** @description Item ID */
        ItemId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "service": "backend"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTrips: {
        parameters: {
            query?: {
                /** @description Filter to upcoming trips only */
                upcoming?: boolean;
                /** @description Filter to past trips only */
                past?: boolean;
                /** @description Filter by trip purpose */
                purpose?: components["schemas"]["TripPurpose"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of trips */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"][];
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "FOSDEM 2025",
                 *       "purpose": "conference",
                 *       "startDate": "2025-01-29",
                 *       "endDate": "2025-02-02",
                 *       "notes": "Annual open source conference in Brussels"
                 *     }
                 */
                "application/json": components["schemas"]["CreateTripRequest"];
            };
        };
        responses: {
            /** @description Trip created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    searchTrips: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"][];
                };
            };
            /** @description Invalid search query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTripRequest"];
            };
        };
        responses: {
            /** @description Trip updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    mergeTrips: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source trip ID (to be merged and deleted) */
                sourceId: string;
                /** @description Target trip ID (will receive items) */
                targetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeTripsRequest"];
            };
        };
        responses: {
            /** @description Trips merged successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Invalid request (e.g., same trip for source and target) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Source or target trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTripItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"][];
                };
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createTripItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemRequest"];
            };
        };
        responses: {
            /** @description Item created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    moveItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID */
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveItemRequest"];
            };
        };
        responses: {
            /** @description Item moved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveItemResponse"];
                };
            };
            /** @description Invalid request (must provide targetTripId or newTrip, or item already on target trip) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Item or target trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                /** @description Filter by trip ID */
                tripId?: string;
                /** @description Return only documents not associated with a trip */
                unassociated?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getBaseLocations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Base locations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseLocations"];
                };
            };
        };
    };
    setBaseLocations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "home": "New York, USA",
                 *       "work": "Manhattan, NYC"
                 *     }
                 */
                "application/json": components["schemas"]["SetBaseLocationsRequest"];
            };
        };
        responses: {
            /** @description Base locations updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseLocations"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTripLocations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip locations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDayLocation"][];
                };
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    setTripLocations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "defaultLocation": "Brussels, Belgium",
                 *       "locations": [
                 *         {
                 *           "date": "2025-01-29",
                 *           "locations": [
                 *             "London, UK",
                 *             "Brussels, Belgium"
                 *           ]
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["SetTripLocationsRequest"];
            };
        };
        responses: {
            /** @description Trip locations updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDayLocation"][];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLocationOnDate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Date to query (YYYY-MM-DD) */
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Location on the specified date */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOnDateResponse"];
                };
            };
            /** @description Invalid date format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLocationRange: {
        parameters: {
            query: {
                /** @description Start date (YYYY-MM-DD) */
                from: string;
                /** @description End date (YYYY-MM-DD) */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Location timeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRangeSegment"][];
                };
            };
            /** @description Invalid date format or range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getGoogleAuthUrl: {
        parameters: {
            query?: {
                /** @description OAuth scopes to request (comma-separated). Defaults to calendar.readonly. */
                scopes?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OAuth URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthUrlResponse"];
                };
            };
        };
    };
    handleGoogleCallback: {
        parameters: {
            query: {
                /** @description Authorization code from Google */
                code: string;
                /** @description State parameter for CSRF protection */
                state?: string;
                /** @description Error from Google if authorization failed */
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to settings page with success or error */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid callback parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getGoogleAuthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authentication status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleAuthStatus"];
                };
            };
        };
    };
    disconnectGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully disconnected */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not connected */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listCalendars: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of calendars */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleCalendar"][];
                };
            };
            /** @description Not authenticated with Google */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSelectedCalendars: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Selected calendars */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCalendar"][];
                };
            };
        };
    };
    setSelectedCalendars: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSelectedCalendarsRequest"];
            };
        };
        responses: {
            /** @description Updated selection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCalendar"][];
                };
            };
            /** @description Not authenticated with Google */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listCalendarEvents: {
        parameters: {
            query: {
                /** @description Start date (YYYY-MM-DD) */
                from: string;
                /** @description End date (YYYY-MM-DD) */
                to: string;
                /** @description Filter to specific calendar */
                calendarId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calendar events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEvent"][];
                };
            };
            /** @description Not authenticated with Google */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCalendarConflicts: {
        parameters: {
            query?: {
                /** @description Check conflicts for specific trip */
                tripId?: string;
                /** @description Start date for range check (YYYY-MM-DD) */
                from?: string;
                /** @description End date for range check (YYYY-MM-DD) */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of conflicts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarConflict"][];
                };
            };
            /** @description Not authenticated with Google */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    suggestTripsFromCalendar: {
        parameters: {
            query?: {
                /** @description Start date (YYYY-MM-DD). Defaults to today. */
                from?: string;
                /** @description End date (YYYY-MM-DD). Defaults to 90 days from now. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip suggestions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripSuggestion"][];
                };
            };
            /** @description Not authenticated with Google */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    importTripSuggestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Suggestion ID to import */
                suggestionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Suggestion not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    dismissTripSuggestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Suggestion ID to dismiss */
                suggestionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Suggestion dismissed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Suggestion not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    mergeTripSuggestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Suggestion ID to merge */
                suggestionId: string;
                /** @description Target trip ID to merge into */
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip updated with merged items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Suggestion or trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    resetProcessedEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Processed events reset */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTripCalendarLinks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calendar links */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarLink"][];
                };
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    syncTripToCalendar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SyncTripRequest"];
            };
        };
        responses: {
            /** @description Sync result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncTripResult"];
                };
            };
            /** @description Not authenticated with Google */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
