/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List activities for the authenticated user */
        get: operations["listActivities"];
        put?: never;
        /** Create a new activity */
        post: operations["createActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single activity by ID */
        get: operations["getActivity"];
        /** Update an activity */
        put: operations["updateActivity"];
        post?: never;
        /** Delete an activity by ID */
        delete: operations["deleteActivity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse freeform text into a proposed activity */
        post: operations["parseActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/check/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check what activities span a specific date */
        get: operations["checkDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Activity: {
            id: string;
            userId: string;
            title: string;
            /** @enum {string} */
            type: "travel" | "stay" | "conference" | "vacation" | "commitment";
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            location?: string;
            notes?: string;
            /** @description Optional trip grouping name (e.g., "FOSDEM 2027") */
            tripName?: string;
            /** @enum {string} */
            source: "manual" | "google_calendar" | "system";
            /** Format: date-time */
            createdAt: string;
        };
        CreateActivityRequest: {
            title: string;
            /** @enum {string} */
            type: "travel" | "stay" | "conference" | "vacation" | "commitment";
            /** Format: date */
            startDate: string;
            /**
             * Format: date
             * @description Defaults to startDate if omitted
             */
            endDate?: string;
            location?: string;
            notes?: string;
            tripName?: string;
            /** @description Optional ID from a prior parse, to link creation to parse history */
            parseHistoryId?: string;
        };
        /** @description All fields optional — only provided fields are updated */
        UpdateActivityRequest: {
            title?: string;
            /** @enum {string} */
            type?: "travel" | "stay" | "conference" | "vacation" | "commitment";
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            location?: string;
            notes?: string;
            tripName?: string;
        };
        DateCheck: {
            /** Format: date */
            date: string;
            /** @description Primary location for the day (Home if no activities) */
            location: string;
            activities: components["schemas"]["Activity"][];
            /** @description True if activities on this date span multiple locations */
            hasConflict: boolean;
        };
        ParseRequest: {
            text: string;
        };
        ParseResult: {
            /** @description Parse history ID, pass back as parseHistoryId when creating */
            id: string;
            activity: components["schemas"]["ParsedActivity"];
            confidence: components["schemas"]["ParseConfidence"];
            unparsed: string;
        };
        /** @description All fields optional — parser fills what it can */
        ParsedActivity: {
            title?: string;
            /** @enum {string} */
            type?: "travel" | "stay" | "conference" | "vacation" | "commitment";
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            location?: string;
            notes?: string;
        };
        ParseConfidence: {
            /** @enum {string} */
            title?: "high" | "medium" | "low";
            /** @enum {string} */
            type?: "high" | "medium" | "low";
            /** @enum {string} */
            startDate?: "high" | "medium" | "low";
            /** @enum {string} */
            endDate?: "high" | "medium" | "low";
            /** @enum {string} */
            location?: "high" | "medium" | "low";
        };
        OkResponse: {
            ok?: string;
        };
        ErrorResponse: {
            error?: string;
        };
    };
    responses: {
        /** @description Not authenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listActivities: {
        parameters: {
            query?: {
                /** @description Filter by month (YYYY-MM) */
                month?: string;
                /** @description Filter start (YYYY-MM-DD), used with 'to' */
                from?: string;
                /** @description Filter end (YYYY-MM-DD), used with 'from' */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of activities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivityRequest"];
            };
        };
        responses: {
            /** @description Created activity */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The activity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActivityRequest"];
            };
        };
        responses: {
            /** @description Updated activity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    parseActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Parse result with proposed activity fields */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    checkDate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Date to check (YYYY-MM-DD) */
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Date check result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DateCheck"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
