/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List activities for the authenticated user */
        get: operations["listActivities"];
        put?: never;
        /** Create a new activity */
        post: operations["createActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single activity by ID */
        get: operations["getActivity"];
        /** Update an activity */
        put: operations["updateActivity"];
        post?: never;
        /** Delete an activity by ID */
        delete: operations["deleteActivity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse freeform text into a proposed activity */
        post: operations["parseActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/check/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check what activities span a specific date */
        get: operations["checkDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's public profile settings */
        get: operations["getPublicProfile"];
        /** Create or update public profile settings */
        put: operations["updatePublicProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List trips for the authenticated user */
        get: operations["listTrips"];
        put?: never;
        /** Create a new trip */
        post: operations["createTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/share-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List share links created by the authenticated user */
        get: operations["listShareLinks"];
        put?: never;
        /** Create a new share link */
        post: operations["createShareLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/share-links/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a share link */
        delete: operations["deleteShareLink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List calendar shares created by the authenticated user */
        get: operations["listShares"];
        put?: never;
        /** Share calendar with another user by email */
        post: operations["createShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a share */
        delete: operations["deleteShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shared-with-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List calendars shared with the authenticated user */
        get: operations["listSharedWithMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shared-with-me/{email}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get privacy-filtered activities from a user who shared with you */
        get: operations["getSharedActivities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a trip */
        put: operations["updateTrip"];
        post?: never;
        /** Delete a trip (activities become standalone) */
        delete: operations["deleteTrip"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Activity: {
            id: string;
            userId: string;
            title: string;
            /** @enum {string} */
            type: "travel" | "stay" | "conference" | "vacation" | "commitment";
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            location?: string;
            notes?: string;
            /** @description Optional trip ID this activity belongs to */
            tripId?: string;
            /** @enum {string} */
            source: "manual" | "google_calendar" | "system";
            /** Format: date-time */
            createdAt: string;
        };
        CreateActivityRequest: {
            title: string;
            /** @enum {string} */
            type: "travel" | "stay" | "conference" | "vacation" | "commitment";
            /** Format: date */
            startDate: string;
            /**
             * Format: date
             * @description Defaults to startDate if omitted
             */
            endDate?: string;
            location?: string;
            notes?: string;
            tripId?: string;
            /** @description Optional ID from a prior parse, to link creation to parse history */
            parseHistoryId?: string;
        };
        /** @description All fields optional — only provided fields are updated */
        UpdateActivityRequest: {
            title?: string;
            /** @enum {string} */
            type?: "travel" | "stay" | "conference" | "vacation" | "commitment";
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            location?: string;
            notes?: string;
            tripId?: string;
        };
        DateCheck: {
            /** Format: date */
            date: string;
            /** @description Primary location for the day (Home if no activities) */
            location: string;
            activities: components["schemas"]["Activity"][];
            /** @description True if activities on this date span multiple locations */
            hasConflict: boolean;
        };
        ParseRequest: {
            text: string;
        };
        ParseResult: {
            /** @description Parse history ID, pass back as parseHistoryId when creating */
            id: string;
            activity: components["schemas"]["ParsedActivity"];
            confidence: components["schemas"]["ParseConfidence"];
            unparsed: string;
        };
        /** @description All fields optional — parser fills what it can */
        ParsedActivity: {
            title?: string;
            /** @enum {string} */
            type?: "travel" | "stay" | "conference" | "vacation" | "commitment";
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            location?: string;
            notes?: string;
        };
        ParseConfidence: {
            /** @enum {string} */
            title?: "high" | "medium" | "low";
            /** @enum {string} */
            type?: "high" | "medium" | "low";
            /** @enum {string} */
            startDate?: "high" | "medium" | "low";
            /** @enum {string} */
            endDate?: "high" | "medium" | "low";
            /** @enum {string} */
            location?: "high" | "medium" | "low";
        };
        Trip: {
            id: string;
            userId: string;
            name: string;
            /** @description Hex color for visual grouping */
            color: string;
            /** Format: date-time */
            createdAt: string;
        };
        TripSummary: {
            id: string;
            name: string;
            color: string;
            /**
             * Format: date
             * @description Earliest activity start date
             */
            startDate: string;
            /**
             * Format: date
             * @description Latest activity end date
             */
            endDate: string;
            locations?: string[];
            activityCount: number;
        };
        CreateTripRequest: {
            name: string;
            /** @description Hex color (auto-assigned if omitted) */
            color?: string;
        };
        UpdateTripRequest: {
            name?: string;
            color?: string;
        };
        ShareLink: {
            id: string;
            /** @description URL-safe token for accessing the shared calendar */
            token: string;
            /** @description User-friendly name for this link */
            label: string;
            /**
             * Format: date-time
             * @description When this link expires (empty = never)
             */
            expiresAt?: string;
            /**
             * Format: date
             * @description Only share activities starting from this date
             */
            fromDate?: string;
            /**
             * Format: date
             * @description Only share activities ending before this date
             */
            toDate?: string;
            /** @description Comma-separated trip IDs to filter by (empty = all) */
            tripIds?: string;
            /** @description Whether activity titles are visible to viewers */
            showTitle: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        CreateShareLinkRequest: {
            /** @description User-friendly name (auto-generated if omitted) */
            label?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date */
            fromDate?: string;
            /** Format: date */
            toDate?: string;
            /** @description Comma-separated trip IDs to filter by */
            tripIds?: string;
            /** @description Whether activity titles are visible (default false) */
            showTitle?: boolean;
        };
        SharedActivity: {
            /** @description Included only if showTitle is enabled on the share */
            title?: string;
            /** @enum {string} */
            type: "travel" | "stay" | "conference" | "vacation" | "commitment";
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            location?: string;
            /** @description Trip name for context (not the ID) */
            tripName?: string;
            /** @description Trip hex color */
            tripColor?: string;
        };
        SharedCalendarResponse: {
            /** @description Share link label or sharer description */
            label: string;
            /** @description Email of the calendar owner */
            ownerEmail?: string;
            activities: components["schemas"]["SharedActivity"][];
        };
        Share: {
            id: string;
            /** @description Email of the user who created this share */
            ownerEmail: string;
            /** @description Email of the recipient */
            sharedWith: string;
            /** @description Whether activity titles are visible to the recipient */
            showTitle: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        CreateShareRequest: {
            /** @description Email of the user to share with */
            email: string;
            /** @description Whether activity titles are visible (default false) */
            showTitle?: boolean;
        };
        SharedWithMeEntry: {
            shareId: string;
            /** @description Email of the person who shared with you */
            ownerEmail: string;
        };
        PublicProfile: {
            /** @description URL slug for the public page (e.g. michael) */
            handle: string;
            /** @description Whether the public page is active */
            enabled: boolean;
        };
        UpdatePublicProfileRequest: {
            /** @description URL slug (lowercase alphanumeric + hyphens, 3-30 chars) */
            handle: string;
            enabled: boolean;
        };
        OkResponse: {
            ok?: string;
        };
        ErrorResponse: {
            error?: string;
        };
    };
    responses: {
        /** @description Not authenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listActivities: {
        parameters: {
            query?: {
                /** @description Filter by month (YYYY-MM) */
                month?: string;
                /** @description Filter start (YYYY-MM-DD), used with 'to' */
                from?: string;
                /** @description Filter end (YYYY-MM-DD), used with 'from' */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of activities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivityRequest"];
            };
        };
        responses: {
            /** @description Created activity */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The activity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActivityRequest"];
            };
        };
        responses: {
            /** @description Updated activity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    parseActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Parse result with proposed activity fields */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    checkDate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Date to check (YYYY-MM-DD) */
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Date check result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DateCheck"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getPublicProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public profile (may not exist yet) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updatePublicProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePublicProfileRequest"];
            };
        };
        responses: {
            /** @description Updated public profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listTrips: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of trips with computed fields */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripRequest"];
            };
        };
        responses: {
            /** @description Created trip */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listShareLinks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of share links */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareLink"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createShareLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShareLinkRequest"];
            };
        };
        responses: {
            /** @description Created share link */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareLink"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteShareLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listShares: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of shares */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Share"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createShare: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShareRequest"];
            };
        };
        responses: {
            /** @description Created share */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Share"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listSharedWithMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of shares where current user is the recipient */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedWithMeEntry"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSharedActivities: {
        parameters: {
            query?: {
                /** @description Filter by month (YYYY-MM) */
                month?: string;
                /** @description Filter start (YYYY-MM-DD) */
                from?: string;
                /** @description Filter end (YYYY-MM-DD) */
                to?: string;
            };
            header?: never;
            path: {
                /** @description Email of the user who shared their calendar */
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Privacy-filtered activities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedCalendarResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTripRequest"];
            };
        };
        responses: {
            /** @description Updated trip */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
