// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionScopes = "session.Scopes"
)

// Defines values for ActivitySource.
const (
	GoogleCalendar ActivitySource = "google_calendar"
	Manual         ActivitySource = "manual"
	System         ActivitySource = "system"
)

// Valid indicates whether the value is a known member of the ActivitySource enum.
func (e ActivitySource) Valid() bool {
	switch e {
	case GoogleCalendar:
		return true
	case Manual:
		return true
	case System:
		return true
	default:
		return false
	}
}

// Defines values for ActivityType.
const (
	ActivityTypeCommitment ActivityType = "commitment"
	ActivityTypeConference ActivityType = "conference"
	ActivityTypeStay       ActivityType = "stay"
	ActivityTypeTravel     ActivityType = "travel"
	ActivityTypeVacation   ActivityType = "vacation"
)

// Valid indicates whether the value is a known member of the ActivityType enum.
func (e ActivityType) Valid() bool {
	switch e {
	case ActivityTypeCommitment:
		return true
	case ActivityTypeConference:
		return true
	case ActivityTypeStay:
		return true
	case ActivityTypeTravel:
		return true
	case ActivityTypeVacation:
		return true
	default:
		return false
	}
}

// Defines values for CreateActivityRequestType.
const (
	CreateActivityRequestTypeCommitment CreateActivityRequestType = "commitment"
	CreateActivityRequestTypeConference CreateActivityRequestType = "conference"
	CreateActivityRequestTypeStay       CreateActivityRequestType = "stay"
	CreateActivityRequestTypeTravel     CreateActivityRequestType = "travel"
	CreateActivityRequestTypeVacation   CreateActivityRequestType = "vacation"
)

// Valid indicates whether the value is a known member of the CreateActivityRequestType enum.
func (e CreateActivityRequestType) Valid() bool {
	switch e {
	case CreateActivityRequestTypeCommitment:
		return true
	case CreateActivityRequestTypeConference:
		return true
	case CreateActivityRequestTypeStay:
		return true
	case CreateActivityRequestTypeTravel:
		return true
	case CreateActivityRequestTypeVacation:
		return true
	default:
		return false
	}
}

// Defines values for ParseConfidenceEndDate.
const (
	ParseConfidenceEndDateHigh   ParseConfidenceEndDate = "high"
	ParseConfidenceEndDateLow    ParseConfidenceEndDate = "low"
	ParseConfidenceEndDateMedium ParseConfidenceEndDate = "medium"
)

// Valid indicates whether the value is a known member of the ParseConfidenceEndDate enum.
func (e ParseConfidenceEndDate) Valid() bool {
	switch e {
	case ParseConfidenceEndDateHigh:
		return true
	case ParseConfidenceEndDateLow:
		return true
	case ParseConfidenceEndDateMedium:
		return true
	default:
		return false
	}
}

// Defines values for ParseConfidenceLocation.
const (
	ParseConfidenceLocationHigh   ParseConfidenceLocation = "high"
	ParseConfidenceLocationLow    ParseConfidenceLocation = "low"
	ParseConfidenceLocationMedium ParseConfidenceLocation = "medium"
)

// Valid indicates whether the value is a known member of the ParseConfidenceLocation enum.
func (e ParseConfidenceLocation) Valid() bool {
	switch e {
	case ParseConfidenceLocationHigh:
		return true
	case ParseConfidenceLocationLow:
		return true
	case ParseConfidenceLocationMedium:
		return true
	default:
		return false
	}
}

// Defines values for ParseConfidenceStartDate.
const (
	ParseConfidenceStartDateHigh   ParseConfidenceStartDate = "high"
	ParseConfidenceStartDateLow    ParseConfidenceStartDate = "low"
	ParseConfidenceStartDateMedium ParseConfidenceStartDate = "medium"
)

// Valid indicates whether the value is a known member of the ParseConfidenceStartDate enum.
func (e ParseConfidenceStartDate) Valid() bool {
	switch e {
	case ParseConfidenceStartDateHigh:
		return true
	case ParseConfidenceStartDateLow:
		return true
	case ParseConfidenceStartDateMedium:
		return true
	default:
		return false
	}
}

// Defines values for ParseConfidenceTitle.
const (
	ParseConfidenceTitleHigh   ParseConfidenceTitle = "high"
	ParseConfidenceTitleLow    ParseConfidenceTitle = "low"
	ParseConfidenceTitleMedium ParseConfidenceTitle = "medium"
)

// Valid indicates whether the value is a known member of the ParseConfidenceTitle enum.
func (e ParseConfidenceTitle) Valid() bool {
	switch e {
	case ParseConfidenceTitleHigh:
		return true
	case ParseConfidenceTitleLow:
		return true
	case ParseConfidenceTitleMedium:
		return true
	default:
		return false
	}
}

// Defines values for ParseConfidenceType.
const (
	High   ParseConfidenceType = "high"
	Low    ParseConfidenceType = "low"
	Medium ParseConfidenceType = "medium"
)

// Valid indicates whether the value is a known member of the ParseConfidenceType enum.
func (e ParseConfidenceType) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for ParsedActivityType.
const (
	ParsedActivityTypeCommitment ParsedActivityType = "commitment"
	ParsedActivityTypeConference ParsedActivityType = "conference"
	ParsedActivityTypeStay       ParsedActivityType = "stay"
	ParsedActivityTypeTravel     ParsedActivityType = "travel"
	ParsedActivityTypeVacation   ParsedActivityType = "vacation"
)

// Valid indicates whether the value is a known member of the ParsedActivityType enum.
func (e ParsedActivityType) Valid() bool {
	switch e {
	case ParsedActivityTypeCommitment:
		return true
	case ParsedActivityTypeConference:
		return true
	case ParsedActivityTypeStay:
		return true
	case ParsedActivityTypeTravel:
		return true
	case ParsedActivityTypeVacation:
		return true
	default:
		return false
	}
}

// Defines values for UpdateActivityRequestType.
const (
	UpdateActivityRequestTypeCommitment UpdateActivityRequestType = "commitment"
	UpdateActivityRequestTypeConference UpdateActivityRequestType = "conference"
	UpdateActivityRequestTypeStay       UpdateActivityRequestType = "stay"
	UpdateActivityRequestTypeTravel     UpdateActivityRequestType = "travel"
	UpdateActivityRequestTypeVacation   UpdateActivityRequestType = "vacation"
)

// Valid indicates whether the value is a known member of the UpdateActivityRequestType enum.
func (e UpdateActivityRequestType) Valid() bool {
	switch e {
	case UpdateActivityRequestTypeCommitment:
		return true
	case UpdateActivityRequestTypeConference:
		return true
	case UpdateActivityRequestTypeStay:
		return true
	case UpdateActivityRequestTypeTravel:
		return true
	case UpdateActivityRequestTypeVacation:
		return true
	default:
		return false
	}
}

// Activity defines model for Activity.
type Activity struct {
	CreatedAt time.Time          `json:"createdAt"`
	EndDate   openapi_types.Date `json:"endDate"`
	Id        string             `json:"id"`
	Location  *string            `json:"location,omitempty"`
	Notes     *string            `json:"notes,omitempty"`
	Source    ActivitySource     `json:"source"`
	StartDate openapi_types.Date `json:"startDate"`
	Title     string             `json:"title"`

	// TripId Optional trip ID this activity belongs to
	TripId *string      `json:"tripId,omitempty"`
	Type   ActivityType `json:"type"`
	UserId string       `json:"userId"`
}

// ActivitySource defines model for Activity.Source.
type ActivitySource string

// ActivityType defines model for Activity.Type.
type ActivityType string

// CreateActivityRequest defines model for CreateActivityRequest.
type CreateActivityRequest struct {
	// EndDate Defaults to startDate if omitted
	EndDate  *openapi_types.Date `json:"endDate,omitempty"`
	Location *string             `json:"location,omitempty"`
	Notes    *string             `json:"notes,omitempty"`

	// ParseHistoryId Optional ID from a prior parse, to link creation to parse history
	ParseHistoryId *string                   `json:"parseHistoryId,omitempty"`
	StartDate      openapi_types.Date        `json:"startDate"`
	Title          string                    `json:"title"`
	TripId         *string                   `json:"tripId,omitempty"`
	Type           CreateActivityRequestType `json:"type"`
}

// CreateActivityRequestType defines model for CreateActivityRequest.Type.
type CreateActivityRequestType string

// CreateTripRequest defines model for CreateTripRequest.
type CreateTripRequest struct {
	// Color Hex color (auto-assigned if omitted)
	Color *string `json:"color,omitempty"`
	Name  string  `json:"name"`
}

// DateCheck defines model for DateCheck.
type DateCheck struct {
	Activities []Activity         `json:"activities"`
	Date       openapi_types.Date `json:"date"`

	// HasConflict True if activities on this date span multiple locations
	HasConflict bool `json:"hasConflict"`

	// Location Primary location for the day (Home if no activities)
	Location string `json:"location"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// OkResponse defines model for OkResponse.
type OkResponse struct {
	Ok *string `json:"ok,omitempty"`
}

// ParseConfidence defines model for ParseConfidence.
type ParseConfidence struct {
	EndDate   *ParseConfidenceEndDate   `json:"endDate,omitempty"`
	Location  *ParseConfidenceLocation  `json:"location,omitempty"`
	StartDate *ParseConfidenceStartDate `json:"startDate,omitempty"`
	Title     *ParseConfidenceTitle     `json:"title,omitempty"`
	Type      *ParseConfidenceType      `json:"type,omitempty"`
}

// ParseConfidenceEndDate defines model for ParseConfidence.EndDate.
type ParseConfidenceEndDate string

// ParseConfidenceLocation defines model for ParseConfidence.Location.
type ParseConfidenceLocation string

// ParseConfidenceStartDate defines model for ParseConfidence.StartDate.
type ParseConfidenceStartDate string

// ParseConfidenceTitle defines model for ParseConfidence.Title.
type ParseConfidenceTitle string

// ParseConfidenceType defines model for ParseConfidence.Type.
type ParseConfidenceType string

// ParseRequest defines model for ParseRequest.
type ParseRequest struct {
	Text string `json:"text"`
}

// ParseResult defines model for ParseResult.
type ParseResult struct {
	// Activity All fields optional — parser fills what it can
	Activity   ParsedActivity  `json:"activity"`
	Confidence ParseConfidence `json:"confidence"`

	// Id Parse history ID, pass back as parseHistoryId when creating
	Id       string `json:"id"`
	Unparsed string `json:"unparsed"`
}

// ParsedActivity All fields optional — parser fills what it can
type ParsedActivity struct {
	EndDate   *openapi_types.Date `json:"endDate,omitempty"`
	Location  *string             `json:"location,omitempty"`
	Notes     *string             `json:"notes,omitempty"`
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
	Title     *string             `json:"title,omitempty"`
	Type      *ParsedActivityType `json:"type,omitempty"`
}

// ParsedActivityType defines model for ParsedActivity.Type.
type ParsedActivityType string

// Trip defines model for Trip.
type Trip struct {
	// Color Hex color for visual grouping
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	UserId    string    `json:"userId"`
}

// TripSummary defines model for TripSummary.
type TripSummary struct {
	ActivityCount int    `json:"activityCount"`
	Color         string `json:"color"`

	// EndDate Latest activity end date
	EndDate   openapi_types.Date `json:"endDate"`
	Id        string             `json:"id"`
	Locations *[]string          `json:"locations,omitempty"`
	Name      string             `json:"name"`

	// StartDate Earliest activity start date
	StartDate openapi_types.Date `json:"startDate"`
}

// UpdateActivityRequest All fields optional — only provided fields are updated
type UpdateActivityRequest struct {
	EndDate   *openapi_types.Date        `json:"endDate,omitempty"`
	Location  *string                    `json:"location,omitempty"`
	Notes     *string                    `json:"notes,omitempty"`
	StartDate *openapi_types.Date        `json:"startDate,omitempty"`
	Title     *string                    `json:"title,omitempty"`
	TripId    *string                    `json:"tripId,omitempty"`
	Type      *UpdateActivityRequestType `json:"type,omitempty"`
}

// UpdateActivityRequestType defines model for UpdateActivityRequest.Type.
type UpdateActivityRequestType string

// UpdateTripRequest defines model for UpdateTripRequest.
type UpdateTripRequest struct {
	Color *string `json:"color,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListActivitiesParams defines parameters for ListActivities.
type ListActivitiesParams struct {
	// Month Filter by month (YYYY-MM)
	Month *string `form:"month,omitempty" json:"month,omitempty"`

	// From Filter start (YYYY-MM-DD), used with 'to'
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To Filter end (YYYY-MM-DD), used with 'from'
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// CreateActivityJSONRequestBody defines body for CreateActivity for application/json ContentType.
type CreateActivityJSONRequestBody = CreateActivityRequest

// ParseActivityJSONRequestBody defines body for ParseActivity for application/json ContentType.
type ParseActivityJSONRequestBody = ParseRequest

// UpdateActivityJSONRequestBody defines body for UpdateActivity for application/json ContentType.
type UpdateActivityJSONRequestBody = UpdateActivityRequest

// CreateTripJSONRequestBody defines body for CreateTrip for application/json ContentType.
type CreateTripJSONRequestBody = CreateTripRequest

// UpdateTripJSONRequestBody defines body for UpdateTrip for application/json ContentType.
type UpdateTripJSONRequestBody = UpdateTripRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List activities for the authenticated user
	// (GET /api/activities)
	ListActivities(w http.ResponseWriter, r *http.Request, params ListActivitiesParams)
	// Create a new activity
	// (POST /api/activities)
	CreateActivity(w http.ResponseWriter, r *http.Request)
	// Check what activities span a specific date
	// (GET /api/activities/check/{date})
	CheckDate(w http.ResponseWriter, r *http.Request, date openapi_types.Date)
	// Parse freeform text into a proposed activity
	// (POST /api/activities/parse)
	ParseActivity(w http.ResponseWriter, r *http.Request)
	// Delete an activity by ID
	// (DELETE /api/activities/{id})
	DeleteActivity(w http.ResponseWriter, r *http.Request, id string)
	// Get a single activity by ID
	// (GET /api/activities/{id})
	GetActivity(w http.ResponseWriter, r *http.Request, id string)
	// Update an activity
	// (PUT /api/activities/{id})
	UpdateActivity(w http.ResponseWriter, r *http.Request, id string)
	// List trips for the authenticated user
	// (GET /api/trips)
	ListTrips(w http.ResponseWriter, r *http.Request)
	// Create a new trip
	// (POST /api/trips)
	CreateTrip(w http.ResponseWriter, r *http.Request)
	// Delete a trip (activities become standalone)
	// (DELETE /api/trips/{id})
	DeleteTrip(w http.ResponseWriter, r *http.Request, id string)
	// Update a trip
	// (PUT /api/trips/{id})
	UpdateTrip(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List activities for the authenticated user
// (GET /api/activities)
func (_ Unimplemented) ListActivities(w http.ResponseWriter, r *http.Request, params ListActivitiesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new activity
// (POST /api/activities)
func (_ Unimplemented) CreateActivity(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check what activities span a specific date
// (GET /api/activities/check/{date})
func (_ Unimplemented) CheckDate(w http.ResponseWriter, r *http.Request, date openapi_types.Date) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Parse freeform text into a proposed activity
// (POST /api/activities/parse)
func (_ Unimplemented) ParseActivity(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an activity by ID
// (DELETE /api/activities/{id})
func (_ Unimplemented) DeleteActivity(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a single activity by ID
// (GET /api/activities/{id})
func (_ Unimplemented) GetActivity(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an activity
// (PUT /api/activities/{id})
func (_ Unimplemented) UpdateActivity(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List trips for the authenticated user
// (GET /api/trips)
func (_ Unimplemented) ListTrips(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new trip
// (POST /api/trips)
func (_ Unimplemented) CreateTrip(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a trip (activities become standalone)
// (DELETE /api/trips/{id})
func (_ Unimplemented) DeleteTrip(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a trip
// (PUT /api/trips/{id})
func (_ Unimplemented) UpdateTrip(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListActivities operation middleware
func (siw *ServerInterfaceWrapper) ListActivities(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListActivitiesParams

	// ------------- Optional query parameter "month" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "month", r.URL.Query(), &params.Month, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "month", Err: err})
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListActivities(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateActivity operation middleware
func (siw *ServerInterfaceWrapper) CreateActivity(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateActivity(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckDate operation middleware
func (siw *ServerInterfaceWrapper) CheckDate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", chi.URLParam(r, "date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckDate(w, r, date)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ParseActivity operation middleware
func (siw *ServerInterfaceWrapper) ParseActivity(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ParseActivity(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteActivity operation middleware
func (siw *ServerInterfaceWrapper) DeleteActivity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteActivity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetActivity operation middleware
func (siw *ServerInterfaceWrapper) GetActivity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActivity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateActivity operation middleware
func (siw *ServerInterfaceWrapper) UpdateActivity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateActivity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTrips operation middleware
func (siw *ServerInterfaceWrapper) ListTrips(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTrips(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTrip operation middleware
func (siw *ServerInterfaceWrapper) CreateTrip(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTrip(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTrip operation middleware
func (siw *ServerInterfaceWrapper) DeleteTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTrip(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTrip operation middleware
func (siw *ServerInterfaceWrapper) UpdateTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTrip(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/activities", wrapper.ListActivities)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/activities", wrapper.CreateActivity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/activities/check/{date}", wrapper.CheckDate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/activities/parse", wrapper.ParseActivity)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/activities/{id}", wrapper.DeleteActivity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/activities/{id}", wrapper.GetActivity)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/activities/{id}", wrapper.UpdateActivity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/trips", wrapper.ListTrips)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/trips", wrapper.CreateTrip)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/trips/{id}", wrapper.DeleteTrip)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/trips/{id}", wrapper.UpdateTrip)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3W7bRhZ+lYPZAk0AOlLaXOnOtdrG2LQN0vQiSLPFmDySpiZn2JlDO1pDwD7EPuE+",
	"yeLMkBQpDSXZtbQusFeRRM6cn+9858+5E6kpSqNRkxOTO2HRlUY79F++kdk7/KNCR/wtNZpQ+4+yLHOV",
	"SlJGj353RvNvLl1gIfnTFxZnYiL+NlpfPQpP3ehba419VwsRq9UqERm61KqSLxMTcalvZK4ysLXgVSJ+",
	"NPSdqXR2OiXeoTOVTRG0IZh52atE/KJlRQtj1T/xhLr8aAhYLmpiCZgJfqc+zrefp6RuFC35c2lNiZZU",
	"wC+1yAfOvYozYwtJYiIySXhGqkCRCFqWKCbCkVV6zjaizqaScOtA7F3lvbD1c26CI6IPtaGg29aT4HF+",
	"hLoqxOSjKKSuZC4SMTdmnuNvqcxRZ9KKRLilIyzEp4hWjqSlg20gRTlG9SGryktvYR+Pn/wHmQO/AJdT",
	"oIVyIGsQ4Apzo+cOyETF+R/WJpKVN8gmOpJLkXBIzdCiTlnZG1k7kn8vCkUFR1vM5sqhvYyhsUoEE0lZ",
	"jtiPjFj7cmN7fV3XceswaGFJOsG01sBc/Y6p5+iFf9qEYidr9COyE159r05xJquc2G/QKgJqBqZQxEGf",
	"7MfygYFXSuvwtXJk7HIn4JdTmFlTgITSKmPBH0xY41zpa/AOUkbzD/4RLMKl4vGitFD6Deo5LcTkZbIr",
	"Zk8TeRvhNRhQwxHz3qpyMFpSkxu7Dchr/Az+ETyTFZkz6Zyaa8w64fI85kUti/1O3DDJn4mpz3ZdLDC9",
	"3la7zgX1N0VYuH1VoM3hLVJCWiv99+zQKFlId2H0LFcpbTvtva08n9bKAYcq5y6+D1wpNRRVTqrMERoq",
	"ubWcK2NylHqTaH0pb60qpF2252FmLNACIZNLePbaFF4HbTpqRKDawKC2t5WadD3cNzuGVL/CbqckfhxP",
	"nVtX/XQ9fI+5PvCSt5wbWGOVebrtSpINWxdqvhCJKDBTVeF9cRstBF1k7nu2l5Lue7jNUPc+uJGXDjs3",
	"6NfBXEL4me5Lfn/m07AoV+U0SP/lPs77S7Iu89NeUOw924mhthvboGO3DMHlNIFSOgdXMr0G6aBf+eB2",
	"gbquYnoeSzCV9icObTRaR/Qs61wz6Nqs29P2TTrPc5gpzDMHpinM//nXv4MtFmYqzx3cLiSBIkglZ4tB",
	"dh2ro3i0FvRINXvL6VyFH1B+ObnfKFfJHObWVOVA2DxgDBkYLZoK/kgNsL8uqe3c1+Gyj36uCi5vw5y/",
	"MFUYCOvjShPO0QZy59E6kww3xW8koaP1bIE6gzqK/uxw1m9NBiJv3YMMOr4X6n3tv5U2Vz39/csHWhAD",
	"bgOv+MDShyKG5C9lFp9VDss0RudLKK25URlmzRvSIlT+3uwvlHGe3jgxANZhY8Kh+WJbDrsQ08oqWv7M",
	"JTZc7NC5GgvFEZEac62wCcSJkGX5W/POmjOl+jsuwyZH6ZmJBFbDhzKXWis9B6kzSOseFjIkTNvmeeYX",
	"YZogeBitayd3bur5N7ioFyNw/vaS3Y02qC3GL16+GLMjTIlalkpMxNcvxi++5hCVtPBGjmSpRv2RZY7e",
	"y+xjjxvHgHijHJ13++5SWlkgsUaTj5s2fqdyQgtXSyiMpgU8+/Dhw4ezH37gbt/78o8K/WRcu9K/JZLO",
	"0qyURGj51X/8+mt292p1xv98tfoilisGxIeE08g+m06fJ1A5zOBW0QK+JPPlgDo85/e02ZutBjTglD0o",
	"n6UMaeD3R4fL/5T0V7dfjcf3WlH+ySl1e23J4QKmO2/yqVfjl0NCWvVHvT1rl5o+zlpSfvzEVrumJAeJ",
	"nfG2GT17y1N2vy/HpXGRIO+vsUSoQejoG5MtH23lG9+Vrfolj2yFqy1QXz6aEmsst7ELCmZt4Q7Ijfcj",
	"1/mDwZHBDiqCBI23HT1XyWY+G6ULTK9Hd8yb1WBy85ucuoHYmdf8WpIM+Ft7zG54zIl1TeOarn1cT0ns",
	"XTGw3mFFgsBbGsy0YdI9NqRelh/dOiz2eykJrsRUzVQauscYzn4A9IUjymw/Vx6Z2L0NxEF8Hj+27ADU",
	"NpphExCADNWHeyjjOiyvW9knSPag/MwiMluA8DOB0mT8Jn7Dimhs3KlsFfqwHEOP3A+Oqf+9Ex0bOSBC",
	"bD+QDNP6lDTubCVjPPa2ZQ/EiA+92n+o/RPt4aAGvYDZ3f7tbAmXU5YZzdHfI/1VEdpVbN9zi9IrtE8I",
	"pO+ROPkqPc8xglNZRXDqj9dHg+rx03d8L3DiPL4rVIKC/4u+7HgRFmzqpoF1Bieryt0D6Xv/xilmn+76",
	"7x7jjzchFFy+tKJ2ZXSScSiIf/gk5BfDx5yCuoudE09A3rYd0w/550978gk69vhyYLNTI/v/RudkjU74",
	"D0PPOrPNFaamQHAkdSZzo/H5nqJ6VNCOVVDvTfHx0SneFNI1xZ9gRWzIvVr9NwAA///TFFmOpSkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
