// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionScopes = "session.Scopes"
)

// Defines values for ActivitySource.
const (
	GoogleCalendar ActivitySource = "google_calendar"
	Manual         ActivitySource = "manual"
	System         ActivitySource = "system"
)

// Valid indicates whether the value is a known member of the ActivitySource enum.
func (e ActivitySource) Valid() bool {
	switch e {
	case GoogleCalendar:
		return true
	case Manual:
		return true
	case System:
		return true
	default:
		return false
	}
}

// Defines values for ActivityType.
const (
	ActivityTypeCommitment ActivityType = "commitment"
	ActivityTypeConference ActivityType = "conference"
	ActivityTypeStay       ActivityType = "stay"
	ActivityTypeTravel     ActivityType = "travel"
	ActivityTypeVacation   ActivityType = "vacation"
)

// Valid indicates whether the value is a known member of the ActivityType enum.
func (e ActivityType) Valid() bool {
	switch e {
	case ActivityTypeCommitment:
		return true
	case ActivityTypeConference:
		return true
	case ActivityTypeStay:
		return true
	case ActivityTypeTravel:
		return true
	case ActivityTypeVacation:
		return true
	default:
		return false
	}
}

// Defines values for CreateActivityRequestType.
const (
	CreateActivityRequestTypeCommitment CreateActivityRequestType = "commitment"
	CreateActivityRequestTypeConference CreateActivityRequestType = "conference"
	CreateActivityRequestTypeStay       CreateActivityRequestType = "stay"
	CreateActivityRequestTypeTravel     CreateActivityRequestType = "travel"
	CreateActivityRequestTypeVacation   CreateActivityRequestType = "vacation"
)

// Valid indicates whether the value is a known member of the CreateActivityRequestType enum.
func (e CreateActivityRequestType) Valid() bool {
	switch e {
	case CreateActivityRequestTypeCommitment:
		return true
	case CreateActivityRequestTypeConference:
		return true
	case CreateActivityRequestTypeStay:
		return true
	case CreateActivityRequestTypeTravel:
		return true
	case CreateActivityRequestTypeVacation:
		return true
	default:
		return false
	}
}

// Defines values for CreatePlaceRequestKind.
const (
	CreatePlaceRequestKindAirport CreatePlaceRequestKind = "airport"
	CreatePlaceRequestKindCity    CreatePlaceRequestKind = "city"
	CreatePlaceRequestKindHome    CreatePlaceRequestKind = "home"
	CreatePlaceRequestKindOther   CreatePlaceRequestKind = "other"
	CreatePlaceRequestKindVenue   CreatePlaceRequestKind = "venue"
	CreatePlaceRequestKindWork    CreatePlaceRequestKind = "work"
)

// Valid indicates whether the value is a known member of the CreatePlaceRequestKind enum.
func (e CreatePlaceRequestKind) Valid() bool {
	switch e {
	case CreatePlaceRequestKindAirport:
		return true
	case CreatePlaceRequestKindCity:
		return true
	case CreatePlaceRequestKindHome:
		return true
	case CreatePlaceRequestKindOther:
		return true
	case CreatePlaceRequestKindVenue:
		return true
	case CreatePlaceRequestKindWork:
		return true
	default:
		return false
	}
}

// Defines values for CreateTripRequestStatus.
const (
	CreateTripRequestStatusConfirmed CreateTripRequestStatus = "confirmed"
	CreateTripRequestStatusPlanned   CreateTripRequestStatus = "planned"
	CreateTripRequestStatusTentative CreateTripRequestStatus = "tentative"
)

// Valid indicates whether the value is a known member of the CreateTripRequestStatus enum.
func (e CreateTripRequestStatus) Valid() bool {
	switch e {
	case CreateTripRequestStatusConfirmed:
		return true
	case CreateTripRequestStatusPlanned:
		return true
	case CreateTripRequestStatusTentative:
		return true
	default:
		return false
	}
}

// Defines values for ParseConfidenceEndDate.
const (
	ParseConfidenceEndDateHigh   ParseConfidenceEndDate = "high"
	ParseConfidenceEndDateLow    ParseConfidenceEndDate = "low"
	ParseConfidenceEndDateMedium ParseConfidenceEndDate = "medium"
)

// Valid indicates whether the value is a known member of the ParseConfidenceEndDate enum.
func (e ParseConfidenceEndDate) Valid() bool {
	switch e {
	case ParseConfidenceEndDateHigh:
		return true
	case ParseConfidenceEndDateLow:
		return true
	case ParseConfidenceEndDateMedium:
		return true
	default:
		return false
	}
}

// Defines values for ParseConfidenceLocation.
const (
	ParseConfidenceLocationHigh   ParseConfidenceLocation = "high"
	ParseConfidenceLocationLow    ParseConfidenceLocation = "low"
	ParseConfidenceLocationMedium ParseConfidenceLocation = "medium"
)

// Valid indicates whether the value is a known member of the ParseConfidenceLocation enum.
func (e ParseConfidenceLocation) Valid() bool {
	switch e {
	case ParseConfidenceLocationHigh:
		return true
	case ParseConfidenceLocationLow:
		return true
	case ParseConfidenceLocationMedium:
		return true
	default:
		return false
	}
}

// Defines values for ParseConfidenceStartDate.
const (
	ParseConfidenceStartDateHigh   ParseConfidenceStartDate = "high"
	ParseConfidenceStartDateLow    ParseConfidenceStartDate = "low"
	ParseConfidenceStartDateMedium ParseConfidenceStartDate = "medium"
)

// Valid indicates whether the value is a known member of the ParseConfidenceStartDate enum.
func (e ParseConfidenceStartDate) Valid() bool {
	switch e {
	case ParseConfidenceStartDateHigh:
		return true
	case ParseConfidenceStartDateLow:
		return true
	case ParseConfidenceStartDateMedium:
		return true
	default:
		return false
	}
}

// Defines values for ParseConfidenceTitle.
const (
	ParseConfidenceTitleHigh   ParseConfidenceTitle = "high"
	ParseConfidenceTitleLow    ParseConfidenceTitle = "low"
	ParseConfidenceTitleMedium ParseConfidenceTitle = "medium"
)

// Valid indicates whether the value is a known member of the ParseConfidenceTitle enum.
func (e ParseConfidenceTitle) Valid() bool {
	switch e {
	case ParseConfidenceTitleHigh:
		return true
	case ParseConfidenceTitleLow:
		return true
	case ParseConfidenceTitleMedium:
		return true
	default:
		return false
	}
}

// Defines values for ParseConfidenceType.
const (
	High   ParseConfidenceType = "high"
	Low    ParseConfidenceType = "low"
	Medium ParseConfidenceType = "medium"
)

// Valid indicates whether the value is a known member of the ParseConfidenceType enum.
func (e ParseConfidenceType) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for ParsedActivityType.
const (
	ParsedActivityTypeCommitment ParsedActivityType = "commitment"
	ParsedActivityTypeConference ParsedActivityType = "conference"
	ParsedActivityTypeStay       ParsedActivityType = "stay"
	ParsedActivityTypeTravel     ParsedActivityType = "travel"
	ParsedActivityTypeVacation   ParsedActivityType = "vacation"
)

// Valid indicates whether the value is a known member of the ParsedActivityType enum.
func (e ParsedActivityType) Valid() bool {
	switch e {
	case ParsedActivityTypeCommitment:
		return true
	case ParsedActivityTypeConference:
		return true
	case ParsedActivityTypeStay:
		return true
	case ParsedActivityTypeTravel:
		return true
	case ParsedActivityTypeVacation:
		return true
	default:
		return false
	}
}

// Defines values for PlaceKind.
const (
	PlaceKindAirport PlaceKind = "airport"
	PlaceKindCity    PlaceKind = "city"
	PlaceKindHome    PlaceKind = "home"
	PlaceKindOther   PlaceKind = "other"
	PlaceKindVenue   PlaceKind = "venue"
	PlaceKindWork    PlaceKind = "work"
)

// Valid indicates whether the value is a known member of the PlaceKind enum.
func (e PlaceKind) Valid() bool {
	switch e {
	case PlaceKindAirport:
		return true
	case PlaceKindCity:
		return true
	case PlaceKindHome:
		return true
	case PlaceKindOther:
		return true
	case PlaceKindVenue:
		return true
	case PlaceKindWork:
		return true
	default:
		return false
	}
}

// Defines values for PlaceSuggestionSource.
const (
	Gazetteer PlaceSuggestionSource = "gazetteer"
	User      PlaceSuggestionSource = "user"
)

// Valid indicates whether the value is a known member of the PlaceSuggestionSource enum.
func (e PlaceSuggestionSource) Valid() bool {
	switch e {
	case Gazetteer:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for SharedActivityType.
const (
	SharedActivityTypeCommitment SharedActivityType = "commitment"
	SharedActivityTypeConference SharedActivityType = "conference"
	SharedActivityTypeStay       SharedActivityType = "stay"
	SharedActivityTypeTravel     SharedActivityType = "travel"
	SharedActivityTypeVacation   SharedActivityType = "vacation"
)

// Valid indicates whether the value is a known member of the SharedActivityType enum.
func (e SharedActivityType) Valid() bool {
	switch e {
	case SharedActivityTypeCommitment:
		return true
	case SharedActivityTypeConference:
		return true
	case SharedActivityTypeStay:
		return true
	case SharedActivityTypeTravel:
		return true
	case SharedActivityTypeVacation:
		return true
	default:
		return false
	}
}

// Defines values for TripStatus.
const (
	TripStatusConfirmed TripStatus = "confirmed"
	TripStatusPlanned   TripStatus = "planned"
	TripStatusTentative TripStatus = "tentative"
)

// Valid indicates whether the value is a known member of the TripStatus enum.
func (e TripStatus) Valid() bool {
	switch e {
	case TripStatusConfirmed:
		return true
	case TripStatusPlanned:
		return true
	case TripStatusTentative:
		return true
	default:
		return false
	}
}

// Defines values for TripSummaryStatus.
const (
	TripSummaryStatusConfirmed TripSummaryStatus = "confirmed"
	TripSummaryStatusPlanned   TripSummaryStatus = "planned"
	TripSummaryStatusTentative TripSummaryStatus = "tentative"
)

// Valid indicates whether the value is a known member of the TripSummaryStatus enum.
func (e TripSummaryStatus) Valid() bool {
	switch e {
	case TripSummaryStatusConfirmed:
		return true
	case TripSummaryStatusPlanned:
		return true
	case TripSummaryStatusTentative:
		return true
	default:
		return false
	}
}

// Defines values for UpdateActivityRequestType.
const (
	Commitment UpdateActivityRequestType = "commitment"
	Conference UpdateActivityRequestType = "conference"
	Stay       UpdateActivityRequestType = "stay"
	Travel     UpdateActivityRequestType = "travel"
	Vacation   UpdateActivityRequestType = "vacation"
)

// Valid indicates whether the value is a known member of the UpdateActivityRequestType enum.
func (e UpdateActivityRequestType) Valid() bool {
	switch e {
	case Commitment:
		return true
	case Conference:
		return true
	case Stay:
		return true
	case Travel:
		return true
	case Vacation:
		return true
	default:
		return false
	}
}

// Defines values for UpdatePlaceRequestKind.
const (
	Airport UpdatePlaceRequestKind = "airport"
	City    UpdatePlaceRequestKind = "city"
	Home    UpdatePlaceRequestKind = "home"
	Other   UpdatePlaceRequestKind = "other"
	Venue   UpdatePlaceRequestKind = "venue"
	Work    UpdatePlaceRequestKind = "work"
)

// Valid indicates whether the value is a known member of the UpdatePlaceRequestKind enum.
func (e UpdatePlaceRequestKind) Valid() bool {
	switch e {
	case Airport:
		return true
	case City:
		return true
	case Home:
		return true
	case Other:
		return true
	case Venue:
		return true
	case Work:
		return true
	default:
		return false
	}
}

// Defines values for UpdateTripRequestStatus.
const (
	UpdateTripRequestStatusConfirmed UpdateTripRequestStatus = "confirmed"
	UpdateTripRequestStatusPlanned   UpdateTripRequestStatus = "planned"
	UpdateTripRequestStatusTentative UpdateTripRequestStatus = "tentative"
)

// Valid indicates whether the value is a known member of the UpdateTripRequestStatus enum.
func (e UpdateTripRequestStatus) Valid() bool {
	switch e {
	case UpdateTripRequestStatusConfirmed:
		return true
	case UpdateTripRequestStatusPlanned:
		return true
	case UpdateTripRequestStatusTentative:
		return true
	default:
		return false
	}
}

// Activity defines model for Activity.
type Activity struct {
	CreatedAt time.Time `json:"createdAt"`

	// DestinationPlaceId Destination place for travel activities
	DestinationPlaceId *string            `json:"destinationPlaceId,omitempty"`
	EndDate            openapi_types.Date `json:"endDate"`
	Id                 string             `json:"id"`
	Location           *string            `json:"location,omitempty"`
	Notes              *string            `json:"notes,omitempty"`

	// OriginPlaceId Origin place for travel activities
	OriginPlaceId *string `json:"originPlaceId,omitempty"`

	// PlaceId Optional reference to a Place entity
	PlaceId   *string            `json:"placeId,omitempty"`
	Source    ActivitySource     `json:"source"`
	StartDate openapi_types.Date `json:"startDate"`
	Title     string             `json:"title"`

	// TripId Optional trip ID this activity belongs to
	TripId *string      `json:"tripId,omitempty"`
	Type   ActivityType `json:"type"`
	UserId string       `json:"userId"`
}

// ActivitySource defines model for Activity.Source.
type ActivitySource string

// ActivityType defines model for Activity.Type.
type ActivityType string

// BulkDeleteRequest defines model for BulkDeleteRequest.
type BulkDeleteRequest struct {
	Ids []string `json:"ids"`
}

// BulkDeleteResponse defines model for BulkDeleteResponse.
type BulkDeleteResponse struct {
	Deleted int `json:"deleted"`
}

// CreateActivityRequest defines model for CreateActivityRequest.
type CreateActivityRequest struct {
	DestinationPlaceId *string `json:"destinationPlaceId,omitempty"`

	// EndDate Defaults to startDate if omitted
	EndDate       *openapi_types.Date `json:"endDate,omitempty"`
	Location      *string             `json:"location,omitempty"`
	Notes         *string             `json:"notes,omitempty"`
	OriginPlaceId *string             `json:"originPlaceId,omitempty"`

	// ParseHistoryId Optional ID from a prior parse, to link creation to parse history
	ParseHistoryId *string                   `json:"parseHistoryId,omitempty"`
	PlaceId        *string                   `json:"placeId,omitempty"`
	StartDate      openapi_types.Date        `json:"startDate"`
	Title          string                    `json:"title"`
	TripId         *string                   `json:"tripId,omitempty"`
	Type           CreateActivityRequestType `json:"type"`
}

// CreateActivityRequestType defines model for CreateActivityRequest.Type.
type CreateActivityRequestType string

// CreatePlaceRequest defines model for CreatePlaceRequest.
type CreatePlaceRequest struct {
	Aliases   *[]string               `json:"aliases,omitempty"`
	City      *string                 `json:"city,omitempty"`
	Country   *string                 `json:"country,omitempty"`
	Kind      *CreatePlaceRequestKind `json:"kind,omitempty"`
	Latitude  *float64                `json:"latitude,omitempty"`
	Longitude *float64                `json:"longitude,omitempty"`
	Name      string                  `json:"name"`
	Timezone  *string                 `json:"timezone,omitempty"`
}

// CreatePlaceRequestKind defines model for CreatePlaceRequest.Kind.
type CreatePlaceRequestKind string

// CreateShareLinkRequest defines model for CreateShareLinkRequest.
type CreateShareLinkRequest struct {
	ExpiresAt *time.Time          `json:"expiresAt,omitempty"`
	FromDate  *openapi_types.Date `json:"fromDate,omitempty"`

	// Label User-friendly name (auto-generated if omitted)
	Label *string `json:"label,omitempty"`

	// ShowTitle Whether activity titles are visible (default false)
	ShowTitle *bool               `json:"showTitle,omitempty"`
	ToDate    *openapi_types.Date `json:"toDate,omitempty"`

	// TripIds Comma-separated trip IDs to filter by
	TripIds *string `json:"tripIds,omitempty"`
}

// CreateShareRequest defines model for CreateShareRequest.
type CreateShareRequest struct {
	// Email Email of the user to share with
	Email string `json:"email"`

	// ShowTitle Whether activity titles are visible (default false)
	ShowTitle *bool `json:"showTitle,omitempty"`
}

// CreateTripRequest defines model for CreateTripRequest.
type CreateTripRequest struct {
	// Color Hex color (auto-assigned if omitted)
	Color     *string                  `json:"color,omitempty"`
	EndDate   *openapi_types.Date      `json:"endDate,omitempty"`
	Name      string                   `json:"name"`
	StartDate *openapi_types.Date      `json:"startDate,omitempty"`
	Status    *CreateTripRequestStatus `json:"status,omitempty"`
}

// CreateTripRequestStatus defines model for CreateTripRequest.Status.
type CreateTripRequestStatus string

// DateCheck defines model for DateCheck.
type DateCheck struct {
	Activities []Activity         `json:"activities"`
	Date       openapi_types.Date `json:"date"`

	// HasConflict True if activities on this date span multiple locations
	HasConflict bool `json:"hasConflict"`

	// Location Primary location for the day (Home if no activities)
	Location string `json:"location"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// OkResponse defines model for OkResponse.
type OkResponse struct {
	Ok *string `json:"ok,omitempty"`
}

// ParseConfidence defines model for ParseConfidence.
type ParseConfidence struct {
	EndDate   *ParseConfidenceEndDate   `json:"endDate,omitempty"`
	Location  *ParseConfidenceLocation  `json:"location,omitempty"`
	StartDate *ParseConfidenceStartDate `json:"startDate,omitempty"`
	Title     *ParseConfidenceTitle     `json:"title,omitempty"`
	Type      *ParseConfidenceType      `json:"type,omitempty"`
}

// ParseConfidenceEndDate defines model for ParseConfidence.EndDate.
type ParseConfidenceEndDate string

// ParseConfidenceLocation defines model for ParseConfidence.Location.
type ParseConfidenceLocation string

// ParseConfidenceStartDate defines model for ParseConfidence.StartDate.
type ParseConfidenceStartDate string

// ParseConfidenceTitle defines model for ParseConfidence.Title.
type ParseConfidenceTitle string

// ParseConfidenceType defines model for ParseConfidence.Type.
type ParseConfidenceType string

// ParseRequest defines model for ParseRequest.
type ParseRequest struct {
	Text string `json:"text"`
}

// ParseResult defines model for ParseResult.
type ParseResult struct {
	// Activity All fields optional — parser fills what it can
	Activity   ParsedActivity  `json:"activity"`
	Confidence ParseConfidence `json:"confidence"`

	// Id Parse history ID, pass back as parseHistoryId when creating
	Id       string `json:"id"`
	Unparsed string `json:"unparsed"`
}

// ParsedActivity All fields optional — parser fills what it can
type ParsedActivity struct {
	EndDate   *openapi_types.Date `json:"endDate,omitempty"`
	Location  *string             `json:"location,omitempty"`
	Notes     *string             `json:"notes,omitempty"`
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
	Title     *string             `json:"title,omitempty"`
	Type      *ParsedActivityType `json:"type,omitempty"`
}

// ParsedActivityType defines model for ParsedActivity.Type.
type ParsedActivityType string

// Place defines model for Place.
type Place struct {
	// Aliases Alternative names
	Aliases *[]string `json:"aliases,omitempty"`

	// City Normalized city name
	City *string `json:"city,omitempty"`

	// Country ISO 3166-1 alpha-2 country code
	Country   *string   `json:"country,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`
	Kind      PlaceKind `json:"kind"`
	Latitude  *float64  `json:"latitude,omitempty"`
	Longitude *float64  `json:"longitude,omitempty"`

	// Name User's preferred name for this place
	Name string `json:"name"`

	// Timezone IANA timezone
	Timezone *string `json:"timezone,omitempty"`
}

// PlaceKind defines model for Place.Kind.
type PlaceKind string

// PlaceResolveRequest defines model for PlaceResolveRequest.
type PlaceResolveRequest struct {
	Text string `json:"text"`
}

// PlaceResolveResponse defines model for PlaceResolveResponse.
type PlaceResolveResponse struct {
	Exact       *Place            `json:"exact,omitempty"`
	Suggestions []PlaceSuggestion `json:"suggestions"`
}

// PlaceSuggestion defines model for PlaceSuggestion.
type PlaceSuggestion struct {
	// Admin1 State/province code (e.g. CT, ON)
	Admin1     *string               `json:"admin1,omitempty"`
	Country    *string               `json:"country,omitempty"`
	Latitude   *float64              `json:"latitude,omitempty"`
	Longitude  *float64              `json:"longitude,omitempty"`
	Name       string                `json:"name"`
	Place      *Place                `json:"place,omitempty"`
	Population *int                  `json:"population,omitempty"`
	Score      float64               `json:"score"`
	Source     PlaceSuggestionSource `json:"source"`
	Timezone   *string               `json:"timezone,omitempty"`
}

// PlaceSuggestionSource defines model for PlaceSuggestion.Source.
type PlaceSuggestionSource string

// PublicProfile defines model for PublicProfile.
type PublicProfile struct {
	// Enabled Whether the public page is active
	Enabled bool `json:"enabled"`

	// Handle URL slug for the public page (e.g. michael)
	Handle string `json:"handle"`
}

// Share defines model for Share.
type Share struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`

	// OwnerEmail Email of the user who created this share
	OwnerEmail string `json:"ownerEmail"`

	// SharedWith Email of the recipient
	SharedWith string `json:"sharedWith"`

	// ShowTitle Whether activity titles are visible to the recipient
	ShowTitle bool `json:"showTitle"`
}

// ShareLink defines model for ShareLink.
type ShareLink struct {
	CreatedAt time.Time `json:"createdAt"`

	// ExpiresAt When this link expires (empty = never)
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// FromDate Only share activities starting from this date
	FromDate *openapi_types.Date `json:"fromDate,omitempty"`
	Id       string              `json:"id"`

	// Label User-friendly name for this link
	Label string `json:"label"`

	// ShowTitle Whether activity titles are visible to viewers
	ShowTitle bool `json:"showTitle"`

	// ToDate Only share activities ending before this date
	ToDate *openapi_types.Date `json:"toDate,omitempty"`

	// Token URL-safe token for accessing the shared calendar
	Token string `json:"token"`

	// TripIds Comma-separated trip IDs to filter by (empty = all)
	TripIds *string `json:"tripIds,omitempty"`
}

// SharedActivity defines model for SharedActivity.
type SharedActivity struct {
	EndDate   openapi_types.Date `json:"endDate"`
	Location  *string            `json:"location,omitempty"`
	StartDate openapi_types.Date `json:"startDate"`

	// Title Included only if showTitle is enabled on the share
	Title *string `json:"title,omitempty"`

	// TripColor Trip hex color
	TripColor *string `json:"tripColor,omitempty"`

	// TripName Trip name for context (not the ID)
	TripName *string            `json:"tripName,omitempty"`
	Type     SharedActivityType `json:"type"`
}

// SharedActivityType defines model for SharedActivity.Type.
type SharedActivityType string

// SharedCalendarResponse defines model for SharedCalendarResponse.
type SharedCalendarResponse struct {
	Activities []SharedActivity `json:"activities"`

	// Label Share link label or sharer description
	Label string `json:"label"`

	// OwnerEmail Email of the calendar owner
	OwnerEmail *string `json:"ownerEmail,omitempty"`
}

// SharedWithMeEntry defines model for SharedWithMeEntry.
type SharedWithMeEntry struct {
	// OwnerEmail Email of the person who shared with you
	OwnerEmail string `json:"ownerEmail"`
	ShareId    string `json:"shareId"`
}

// Trip defines model for Trip.
type Trip struct {
	// Color Hex color for visual grouping
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`

	// Status Trip status
	Status TripStatus `json:"status"`
	UserId string     `json:"userId"`
}

// TripStatus Trip status
type TripStatus string

// TripSummary defines model for TripSummary.
type TripSummary struct {
	ActivityCount int    `json:"activityCount"`
	Color         string `json:"color"`

	// EndDate Trip end date (explicit or latest activity)
	EndDate   openapi_types.Date `json:"endDate"`
	Id        string             `json:"id"`
	Locations *[]string          `json:"locations,omitempty"`
	Name      string             `json:"name"`

	// StartDate Trip start date (explicit or earliest activity)
	StartDate openapi_types.Date `json:"startDate"`
	Status    TripSummaryStatus  `json:"status"`
}

// TripSummaryStatus defines model for TripSummary.Status.
type TripSummaryStatus string

// UpdateActivityRequest All fields optional — only provided fields are updated
type UpdateActivityRequest struct {
	DestinationPlaceId *string                    `json:"destinationPlaceId,omitempty"`
	EndDate            *openapi_types.Date        `json:"endDate,omitempty"`
	Location           *string                    `json:"location,omitempty"`
	Notes              *string                    `json:"notes,omitempty"`
	OriginPlaceId      *string                    `json:"originPlaceId,omitempty"`
	PlaceId            *string                    `json:"placeId,omitempty"`
	StartDate          *openapi_types.Date        `json:"startDate,omitempty"`
	Title              *string                    `json:"title,omitempty"`
	TripId             *string                    `json:"tripId,omitempty"`
	Type               *UpdateActivityRequestType `json:"type,omitempty"`
}

// UpdateActivityRequestType defines model for UpdateActivityRequest.Type.
type UpdateActivityRequestType string

// UpdatePlaceRequest defines model for UpdatePlaceRequest.
type UpdatePlaceRequest struct {
	Aliases   *[]string               `json:"aliases,omitempty"`
	City      *string                 `json:"city,omitempty"`
	Country   *string                 `json:"country,omitempty"`
	Kind      *UpdatePlaceRequestKind `json:"kind,omitempty"`
	Latitude  *float64                `json:"latitude,omitempty"`
	Longitude *float64                `json:"longitude,omitempty"`
	Name      *string                 `json:"name,omitempty"`
	Timezone  *string                 `json:"timezone,omitempty"`
}

// UpdatePlaceRequestKind defines model for UpdatePlaceRequest.Kind.
type UpdatePlaceRequestKind string

// UpdatePublicProfileRequest defines model for UpdatePublicProfileRequest.
type UpdatePublicProfileRequest struct {
	Enabled bool `json:"enabled"`

	// Handle URL slug (lowercase alphanumeric + hyphens, 3-30 chars)
	Handle string `json:"handle"`
}

// UpdateTripRequest defines model for UpdateTripRequest.
type UpdateTripRequest struct {
	Color     *string                  `json:"color,omitempty"`
	EndDate   *openapi_types.Date      `json:"endDate,omitempty"`
	Name      *string                  `json:"name,omitempty"`
	StartDate *openapi_types.Date      `json:"startDate,omitempty"`
	Status    *UpdateTripRequestStatus `json:"status,omitempty"`
}

// UpdateTripRequestStatus defines model for UpdateTripRequest.Status.
type UpdateTripRequestStatus string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListActivitiesParams defines parameters for ListActivities.
type ListActivitiesParams struct {
	// Month Filter by month (YYYY-MM)
	Month *string `form:"month,omitempty" json:"month,omitempty"`

	// From Filter start (YYYY-MM-DD), used with 'to'
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To Filter end (YYYY-MM-DD), used with 'from'
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// GetSharedActivitiesParams defines parameters for GetSharedActivities.
type GetSharedActivitiesParams struct {
	// Month Filter by month (YYYY-MM)
	Month *string `form:"month,omitempty" json:"month,omitempty"`

	// From Filter start (YYYY-MM-DD)
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To Filter end (YYYY-MM-DD)
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// CreateActivityJSONRequestBody defines body for CreateActivity for application/json ContentType.
type CreateActivityJSONRequestBody = CreateActivityRequest

// BulkDeleteActivitiesJSONRequestBody defines body for BulkDeleteActivities for application/json ContentType.
type BulkDeleteActivitiesJSONRequestBody = BulkDeleteRequest

// ParseActivityJSONRequestBody defines body for ParseActivity for application/json ContentType.
type ParseActivityJSONRequestBody = ParseRequest

// UpdateActivityJSONRequestBody defines body for UpdateActivity for application/json ContentType.
type UpdateActivityJSONRequestBody = UpdateActivityRequest

// CreatePlaceJSONRequestBody defines body for CreatePlace for application/json ContentType.
type CreatePlaceJSONRequestBody = CreatePlaceRequest

// ResolvePlacesJSONRequestBody defines body for ResolvePlaces for application/json ContentType.
type ResolvePlacesJSONRequestBody = PlaceResolveRequest

// UpdatePlaceJSONRequestBody defines body for UpdatePlace for application/json ContentType.
type UpdatePlaceJSONRequestBody = UpdatePlaceRequest

// UpdatePublicProfileJSONRequestBody defines body for UpdatePublicProfile for application/json ContentType.
type UpdatePublicProfileJSONRequestBody = UpdatePublicProfileRequest

// CreateShareLinkJSONRequestBody defines body for CreateShareLink for application/json ContentType.
type CreateShareLinkJSONRequestBody = CreateShareLinkRequest

// CreateShareJSONRequestBody defines body for CreateShare for application/json ContentType.
type CreateShareJSONRequestBody = CreateShareRequest

// CreateTripJSONRequestBody defines body for CreateTrip for application/json ContentType.
type CreateTripJSONRequestBody = CreateTripRequest

// UpdateTripJSONRequestBody defines body for UpdateTrip for application/json ContentType.
type UpdateTripJSONRequestBody = UpdateTripRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List activities for the authenticated user
	// (GET /api/activities)
	ListActivities(w http.ResponseWriter, r *http.Request, params ListActivitiesParams)
	// Create a new activity
	// (POST /api/activities)
	CreateActivity(w http.ResponseWriter, r *http.Request)
	// Delete multiple activities by ID
	// (POST /api/activities/bulk-delete)
	BulkDeleteActivities(w http.ResponseWriter, r *http.Request)
	// Check what activities span a specific date
	// (GET /api/activities/check/{date})
	CheckDate(w http.ResponseWriter, r *http.Request, date openapi_types.Date)
	// Parse freeform text into a proposed activity
	// (POST /api/activities/parse)
	ParseActivity(w http.ResponseWriter, r *http.Request)
	// Delete an activity by ID
	// (DELETE /api/activities/{id})
	DeleteActivity(w http.ResponseWriter, r *http.Request, id string)
	// Get a single activity by ID
	// (GET /api/activities/{id})
	GetActivity(w http.ResponseWriter, r *http.Request, id string)
	// Update an activity
	// (PUT /api/activities/{id})
	UpdateActivity(w http.ResponseWriter, r *http.Request, id string)
	// List the authenticated user's places
	// (GET /api/places)
	ListPlaces(w http.ResponseWriter, r *http.Request)
	// Create a new place
	// (POST /api/places)
	CreatePlace(w http.ResponseWriter, r *http.Request)
	// Resolve a text string to matching places
	// (POST /api/places/resolve)
	ResolvePlaces(w http.ResponseWriter, r *http.Request)
	// Delete a place
	// (DELETE /api/places/{id})
	DeletePlace(w http.ResponseWriter, r *http.Request, id string)
	// Get a place by ID
	// (GET /api/places/{id})
	GetPlace(w http.ResponseWriter, r *http.Request, id string)
	// Update a place
	// (PUT /api/places/{id})
	UpdatePlace(w http.ResponseWriter, r *http.Request, id string)
	// Get the authenticated user's public profile settings
	// (GET /api/public-profile)
	GetPublicProfile(w http.ResponseWriter, r *http.Request)
	// Create or update public profile settings
	// (PUT /api/public-profile)
	UpdatePublicProfile(w http.ResponseWriter, r *http.Request)
	// List share links created by the authenticated user
	// (GET /api/share-links)
	ListShareLinks(w http.ResponseWriter, r *http.Request)
	// Create a new share link
	// (POST /api/share-links)
	CreateShareLink(w http.ResponseWriter, r *http.Request)
	// Revoke a share link
	// (DELETE /api/share-links/{id})
	DeleteShareLink(w http.ResponseWriter, r *http.Request, id string)
	// List calendars shared with the authenticated user
	// (GET /api/shared-with-me)
	ListSharedWithMe(w http.ResponseWriter, r *http.Request)
	// Get privacy-filtered activities from a user who shared with you
	// (GET /api/shared-with-me/{email}/activities)
	GetSharedActivities(w http.ResponseWriter, r *http.Request, email string, params GetSharedActivitiesParams)
	// List calendar shares created by the authenticated user
	// (GET /api/shares)
	ListShares(w http.ResponseWriter, r *http.Request)
	// Share calendar with another user by email
	// (POST /api/shares)
	CreateShare(w http.ResponseWriter, r *http.Request)
	// Revoke a share
	// (DELETE /api/shares/{id})
	DeleteShare(w http.ResponseWriter, r *http.Request, id string)
	// List trips for the authenticated user
	// (GET /api/trips)
	ListTrips(w http.ResponseWriter, r *http.Request)
	// Create a new trip
	// (POST /api/trips)
	CreateTrip(w http.ResponseWriter, r *http.Request)
	// Delete a trip (activities become standalone)
	// (DELETE /api/trips/{id})
	DeleteTrip(w http.ResponseWriter, r *http.Request, id string)
	// Update a trip
	// (PUT /api/trips/{id})
	UpdateTrip(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List activities for the authenticated user
// (GET /api/activities)
func (_ Unimplemented) ListActivities(w http.ResponseWriter, r *http.Request, params ListActivitiesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new activity
// (POST /api/activities)
func (_ Unimplemented) CreateActivity(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete multiple activities by ID
// (POST /api/activities/bulk-delete)
func (_ Unimplemented) BulkDeleteActivities(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check what activities span a specific date
// (GET /api/activities/check/{date})
func (_ Unimplemented) CheckDate(w http.ResponseWriter, r *http.Request, date openapi_types.Date) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Parse freeform text into a proposed activity
// (POST /api/activities/parse)
func (_ Unimplemented) ParseActivity(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an activity by ID
// (DELETE /api/activities/{id})
func (_ Unimplemented) DeleteActivity(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a single activity by ID
// (GET /api/activities/{id})
func (_ Unimplemented) GetActivity(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an activity
// (PUT /api/activities/{id})
func (_ Unimplemented) UpdateActivity(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List the authenticated user's places
// (GET /api/places)
func (_ Unimplemented) ListPlaces(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new place
// (POST /api/places)
func (_ Unimplemented) CreatePlace(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Resolve a text string to matching places
// (POST /api/places/resolve)
func (_ Unimplemented) ResolvePlaces(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a place
// (DELETE /api/places/{id})
func (_ Unimplemented) DeletePlace(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a place by ID
// (GET /api/places/{id})
func (_ Unimplemented) GetPlace(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a place
// (PUT /api/places/{id})
func (_ Unimplemented) UpdatePlace(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the authenticated user's public profile settings
// (GET /api/public-profile)
func (_ Unimplemented) GetPublicProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create or update public profile settings
// (PUT /api/public-profile)
func (_ Unimplemented) UpdatePublicProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List share links created by the authenticated user
// (GET /api/share-links)
func (_ Unimplemented) ListShareLinks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new share link
// (POST /api/share-links)
func (_ Unimplemented) CreateShareLink(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke a share link
// (DELETE /api/share-links/{id})
func (_ Unimplemented) DeleteShareLink(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List calendars shared with the authenticated user
// (GET /api/shared-with-me)
func (_ Unimplemented) ListSharedWithMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get privacy-filtered activities from a user who shared with you
// (GET /api/shared-with-me/{email}/activities)
func (_ Unimplemented) GetSharedActivities(w http.ResponseWriter, r *http.Request, email string, params GetSharedActivitiesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List calendar shares created by the authenticated user
// (GET /api/shares)
func (_ Unimplemented) ListShares(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Share calendar with another user by email
// (POST /api/shares)
func (_ Unimplemented) CreateShare(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke a share
// (DELETE /api/shares/{id})
func (_ Unimplemented) DeleteShare(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List trips for the authenticated user
// (GET /api/trips)
func (_ Unimplemented) ListTrips(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new trip
// (POST /api/trips)
func (_ Unimplemented) CreateTrip(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a trip (activities become standalone)
// (DELETE /api/trips/{id})
func (_ Unimplemented) DeleteTrip(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a trip
// (PUT /api/trips/{id})
func (_ Unimplemented) UpdateTrip(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListActivities operation middleware
func (siw *ServerInterfaceWrapper) ListActivities(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListActivitiesParams

	// ------------- Optional query parameter "month" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "month", r.URL.Query(), &params.Month, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "month", Err: err})
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListActivities(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateActivity operation middleware
func (siw *ServerInterfaceWrapper) CreateActivity(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateActivity(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BulkDeleteActivities operation middleware
func (siw *ServerInterfaceWrapper) BulkDeleteActivities(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BulkDeleteActivities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckDate operation middleware
func (siw *ServerInterfaceWrapper) CheckDate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", chi.URLParam(r, "date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckDate(w, r, date)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ParseActivity operation middleware
func (siw *ServerInterfaceWrapper) ParseActivity(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ParseActivity(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteActivity operation middleware
func (siw *ServerInterfaceWrapper) DeleteActivity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteActivity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetActivity operation middleware
func (siw *ServerInterfaceWrapper) GetActivity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActivity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateActivity operation middleware
func (siw *ServerInterfaceWrapper) UpdateActivity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateActivity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlaces operation middleware
func (siw *ServerInterfaceWrapper) ListPlaces(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlaces(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePlace operation middleware
func (siw *ServerInterfaceWrapper) CreatePlace(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePlace(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResolvePlaces operation middleware
func (siw *ServerInterfaceWrapper) ResolvePlaces(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResolvePlaces(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePlace operation middleware
func (siw *ServerInterfaceWrapper) DeletePlace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePlace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlace operation middleware
func (siw *ServerInterfaceWrapper) GetPlace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePlace operation middleware
func (siw *ServerInterfaceWrapper) UpdatePlace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePlace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicProfile operation middleware
func (siw *ServerInterfaceWrapper) GetPublicProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePublicProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdatePublicProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePublicProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListShareLinks operation middleware
func (siw *ServerInterfaceWrapper) ListShareLinks(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListShareLinks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateShareLink operation middleware
func (siw *ServerInterfaceWrapper) CreateShareLink(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateShareLink(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteShareLink operation middleware
func (siw *ServerInterfaceWrapper) DeleteShareLink(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteShareLink(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSharedWithMe operation middleware
func (siw *ServerInterfaceWrapper) ListSharedWithMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSharedWithMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSharedActivities operation middleware
func (siw *ServerInterfaceWrapper) GetSharedActivities(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "email" -------------
	var email string

	err = runtime.BindStyledParameterWithOptions("simple", "email", chi.URLParam(r, "email"), &email, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "email", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSharedActivitiesParams

	// ------------- Optional query parameter "month" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "month", r.URL.Query(), &params.Month, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "month", Err: err})
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSharedActivities(w, r, email, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListShares operation middleware
func (siw *ServerInterfaceWrapper) ListShares(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListShares(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateShare operation middleware
func (siw *ServerInterfaceWrapper) CreateShare(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateShare(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteShare operation middleware
func (siw *ServerInterfaceWrapper) DeleteShare(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteShare(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTrips operation middleware
func (siw *ServerInterfaceWrapper) ListTrips(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTrips(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTrip operation middleware
func (siw *ServerInterfaceWrapper) CreateTrip(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTrip(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTrip operation middleware
func (siw *ServerInterfaceWrapper) DeleteTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTrip(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTrip operation middleware
func (siw *ServerInterfaceWrapper) UpdateTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTrip(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/activities", wrapper.ListActivities)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/activities", wrapper.CreateActivity)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/activities/bulk-delete", wrapper.BulkDeleteActivities)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/activities/check/{date}", wrapper.CheckDate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/activities/parse", wrapper.ParseActivity)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/activities/{id}", wrapper.DeleteActivity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/activities/{id}", wrapper.GetActivity)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/activities/{id}", wrapper.UpdateActivity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/places", wrapper.ListPlaces)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/places", wrapper.CreatePlace)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/places/resolve", wrapper.ResolvePlaces)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/places/{id}", wrapper.DeletePlace)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/places/{id}", wrapper.GetPlace)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/places/{id}", wrapper.UpdatePlace)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/public-profile", wrapper.GetPublicProfile)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/public-profile", wrapper.UpdatePublicProfile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/share-links", wrapper.ListShareLinks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/share-links", wrapper.CreateShareLink)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/share-links/{id}", wrapper.DeleteShareLink)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/shared-with-me", wrapper.ListSharedWithMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/shared-with-me/{email}/activities", wrapper.GetSharedActivities)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/shares", wrapper.ListShares)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/shares", wrapper.CreateShare)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/shares/{id}", wrapper.DeleteShare)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/trips", wrapper.ListTrips)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/trips", wrapper.CreateTrip)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/trips/{id}", wrapper.DeleteTrip)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/trips/{id}", wrapper.UpdateTrip)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc727bOBJ/FUK3QBOc3KTbYj8EuA/dpLsbXLct2hSLottb0NLY4poitSRlxy0M3EPc",
	"E96THEjqr0XacmqpKa6f4lgUOcOZ+c0fDv0piHiacQZMyeDiUyBAZpxJMP/8iOPX8FcOUun/Is4UMPMR",
	"ZxklEVaEs7M/JWf6OxklkGL96TsBs+Ai+NtZPfWZfSrPngnBxetikWCz2YRBDDISJNOTBRfBNVtiSmIk",
	"ioU3YfCCq594zuLxiHgNkuciAsS4QjOz9iYM3jKcq4QL8hFGpOUFV0ivC0zpFSAO9JjidT3700iRJVFr",
	"/TkTPAOhiJVfJEC/8NSQOOMixSq4CGKsYKJICkEYqHUGwUUglSBsHti1FWGGkVcUR3BtOG1TdFWPQZke",
	"hGZcICXwEijClhpNgWN6YPEVVtChxzWWmKU7X1Nu99n5kHFlWe884YLMiZ+nl+bxoexk3unMB0yRgBkI",
	"YBEgxRFGZn2kRanWrgmt2un5gOVpcPE+SDHLMQ3CYM75nMIfEabAYiyCMJBrqSANPrjmUVio3jutiKLg",
	"3DUlSLaTPz0AXV8hlRBZbtYaTYFyNpdIcedy5ouaRbvVgaFa70rEWbFpQRgscSFu/X2aEpVqk3PxnEsQ",
	"1y6d2YSBRhMitNm+13pVDS55L6ZrblytrJVYwoZF1RTw6Z8QGaD6MaeLK6CgoAGbbZMksf2jIHXrafEF",
	"FgKvHaTLvQsXSNJZOTbPm/tDmII5iM4q5UjXSpdmA0rI8bLphpFdcLANMTOcU6U1CFUiQWSGeEqUpi3c",
	"r9XHAoqu1WMh4RciFRfrncZxfYVmgqcIo0wQLpB5MdQ8UcIWyCiTBlHF7SOU2En3QM2xrD0l7DmwuUqC",
	"i0fhLtsfx4K3tNBrmH61NELz6iSmBBeBTV/zC4OocKydgRHPmRLuZwtig5VyexJunO2Ki0UQBpiIjAsV",
	"FJOHwRJYrp9zlYBwQhvFiqg83pIvz6e0IWGWp1NtzVrz2fyQ8QynvRSCpPCRM9gPsWZCv5zeJFjAc8IW",
	"XlnBbUYEyEMiF21pvW2A4inQruW+lSAmM0GAxXSNNBfoBOeKT+bAQGjkb2DQqdOBJ3x1UxpYe/LfEtAC",
	"rr2k0XCJsAC0JJJMKaCT2AIfmmEqobHClHMKmBkx8P6mbkxYdmm55GmKJxIybLkq3LjB2xmhCgSaOmBo",
	"s1ukfnGmmDi2+5n+GvEZUgkg7ZEN3OuZ0Iqo5Ivs75YmW8r9qnwjSOZlO+KUiy6hv8AtMo8K5cJSkjnb",
	"r1uHBM89TfowzyEVVrlsIltGMWPGHWvIJyI1n3VWhBVZwn6U9yKFJuoygWjhAPI6Jm9i+a4sq8qRHBAf",
	"92U/wfKSsxklkeoK9UbkJkCpiUPas+uwWM+HZIYZSnOqSEYBlbGJdFp4M3Jpr/JKkBSLdfW+TVUSQDFe",
	"o5NfeGpoYLxBxmmwTwYFv9WqYdDKeppsuyTVzmC7tq8fu11GZ6qXC/88fNFzklc6lNIUk9hEIF2Kajuq",
	"PDSZa7hJISZ5avZi5XbEDckc+m7L1g59uQraDn5xK1Tr9553X71Yp+BW7QWc7RBPv/PBv5TMqfKa/3qf",
	"zZtJ4qblRy2l2PtuQ4eqcsSWOTajdnR9FaIMS4mmOFogLFE7UUCrBFgR9LO5C2ByZt7om8NWG9HirDGN",
	"d2vjZs2ozdJTStGMAI0l4mUe899//8fyInRwQCVaJVgholCENVp4rWuoFO1o1Y2B0pjupuvEZGdGsi0E",
	"BYIZF2qiUA3Dh+cs23VEkWJKPkKM9AAzr2u7GonNVmX2zUv0+NEPP0weIUyzBE++R8VYFPHYPdfhBUhP",
	"1e9rTam6+cUDiTJTFRQQ2xTD+nAibfUx2JN5bQnl6YunqHoc9oGNQvBmR/dVtIqMWnK6HAv6Wyt6g4pb",
	"bIOwnSButlPjRT6fg7TxVt+I0bz8pnpxb2muuYaXr8Z8XTCIU8IedSX8RmEFZ5ngS8IiMKaGTuDh/CG6",
	"vAnRyxene4z4S2m+u4LVW2YZz3K67RyqimUYyIiLviR1q+o62QzCYI4/glLggYj+9Y6qPlzYliXOqQb5",
	"lJLoleAzQp2hKZ5SiP3JrY71MzMHyvAcUFl1B2cikWAWu1Llt6+fI0nzeZU+NKe0ypWSKMFA92cPxRph",
	"RbuLbVMeOMoBlcc/8BUD8axvmWGVcFSsbZHXFB3c9QYsIP6NaFDbOa+AiGREhwTHr1oo7lvCV7YwQN/Y",
	"kxYjTXr2OYCqVHcU4bXKep19KNJlUxsvRqITSDO1Rv9ADJYgTrfr/r2qgVvVeUbXRZGpkaubkJKwuS3Y",
	"V2l7n3MG3zll7xJj5f8158Ooz5LACoTcU0/ss1HAYr1NU5hxAYdtlOILYE4wmkg803QuwFY0cBSBlHod",
	"rfdWdVHj5PPIhc5ayzDtgXjGuCwzpZgPNqnYf2p/tATqjmnSdj9GRPMYYsS1OpAZqhjVvqfAfFvqAj+M",
	"6m2/dFdDb7REkrIk6nv5hTOeNu9WNmT6MW4VOmFcGXKur05HO3/ejm/9x8l+nbgsNNwf996h9Lmlbo58",
	"0YNU5kWLxmYE4sIKWKDmwPAznHFp0si8sdfwSltr7IJ/M7Wr+xWelWHwVjGxL4UZCMmZCRgKGFoRlaA1",
	"z73RQp8ehHJga69cvGgNv8PBgjaHJZE5pmgueJ55Ck7Hi7+8UX99ZuAw3eJh+BnnCXft+ygi9RJ0Kkp2",
	"Y7em+k2eptilVKUPvtTJlztrqQTXvxXCbBSw2B4jnMBtRklElLZGihVIVfn+08+JVqoDiYOOx3eJvfY9",
	"bskL5WAJsKDkYKYGOJgiu5TE3SXUlr9Lfd5msbt7pl8N1rhgUwnQDrkYoUE6N/PGnVrs4W04X7Cr5v+h",
	"wcWjEd8aV45ca9pduvFJoVmb8fcy1CWaOxRcTihfgYiwBFtEZ3kKgkTo7yhZZwkwGaLHk8fnKEqwkEcq",
	"vlju+nUqHKXp4H60GWztg54YolwQtX6jQ2PLuNR5pkUzogUVcb4gVSXvIsBZ9kc5pjayjPwT1rZZm7AZ",
	"dyB4mY4bynUii1msExRzjI5iUBBV5/cz0+vOVNFzXOTpFsSCG9uHXKYG6Omra2N5wpIdnD989PDcIGwG",
	"DGckuAgePzx/+Fj7AqwSw+QZzshZO3WYg9ECrQMGuzQOBs+JVE+bR/86a05BaYou3m/z+FOVPqecqQSd",
	"vHv37t3k11+11pq9/CsH08tYbKUZFYSNvvgMKwVCD/3X77/Hn55sJvrP95vvXHrvWd4GEuXak6ur0xDl",
	"sozTHyj+wEPOTPC0Rc0evfRSoGMz7/p6FR8Fpju6//ofwvbtjO/Pzw+6hfCZjTLdmwlaXXSe1NCsTRg8",
	"OX/kW6Qi/6x1laJpmkbPKqN8/0FzLcuA267YKEaV5evW/QhT4rVHCNKh5O0O5sDiKUj1I4/XR7vV4W6T",
	"3rThW4kcNh2hPjoaEbUsu7K7LKrfuCHvJ1ahdkuucSdoYGFbEhFGDFYNOjfhNp6dTXO6mNiudQMrTrnX",
	"PfItiBtC+t17AL0kfz4IAf6bRWaEdkLCdtoMLE9LUN0D17Dj6RpdXzlFGyUQLc4+aUjceP2W6RMskrCd",
	"LsvcIlAcmVlboF1CtPaZNUIXSNwW3JiYvUvIdYekS7aaU8vmONI1lNjGoOaxSoYZwkhmEJEZiexRgUvO",
	"pr3Ib7yma2lgzG71t41ssM2GN4c0bZ+ZFaQNLHT4zmUDwItywD3EcUv8TABoa0GmRE+YuQ7X4cKpG59I",
	"vKlvMHWVo4Xq6y4GOAzbVHf8Zj2mGTd6Xn0YDfEdZaRferL/peqC7cFgrq27uvRnQTx0Y/TPoL5WCe2K",
	"o24S2Iqh7pGQfgalwZewee1uG3LKcoec2iXKwUR1fPh211ZHxvFdqmIJ/BIh93AaZnlqwkCN4Kagu7vY",
	"8MoOGSOxrRrL+ma1BfljZLTuFPaBbNCwK5d9VbSNDpfIturTI2exheD8KWxWSvY+568FkW3b0GtwutwR",
	"9xaNsA07GSDudfT4jh3+upp+Pb/LQfNGzjq4fRZEIWzjVuvEdAqZYhUl+nNpo1ui7Re0lqb7LWIdLWKt",
	"8cIXp36VQvHCpI5QGxB578JT+5MrfYLSYeUyVER6uO8cQSnKWHRk3zl8INpxtOZMd5LVDfdeq2915g8p",
	"lNZCrmpP0YxvR6CTFK/ND1HBrQ4W16BOh/Z62jL9QWmbPAlKETaX+4y3s72DGZzrGH9sw9sn48oAW5t5",
	"f6NYLoomI7/4S5MzvY0TSthid/JXXS0YJwGsbzIckATKqgd2nEywsV51QWW6vuMZZ83xkLlh58dcRs4P",
	"G3L154j1vt73RLFJqcOieuYVTdF/yy0Gjz5ew5IvtAS90osnK6KSSQr7IbHoXB8PFFut8oeCo0SrBASg",
	"KBcCmLL364jcurA2BnaWlwlkq1PfB51u6Zx9Mj/4s+nTLfUzqNbdih4tU+6biAW5KgEimrecHJYKxW2+",
	"/sYafi1tW2O3ad2Ppqz9xtm5FOTKGARZ4mg9sTfa6jOGu7dkDZv1Z356y19M3LaO6tpN23J7hJgjhpeH",
	"o+eoyFgi9nEiy+Gjyi8ZUe6NJu9hIGlv7FXSNiaDmenOt/Y0XSPrQbaM6JCo8ltEOX5EWctLCZLtxrwb",
	"M2IMyGtehjsA+AwLVjn1pLmq7jKNc9hqlr9757C5kTkk9DUvaoyMfIa3HcCnzPP7nUBbGlv20hPeCsl+",
	"Q7fxzuLMzzGcNDuBIeIp6PSAxZhyBqd76sqDCm2oEvXBJn4+uImXBenaxO/j6U5h3JvN/wIAAP//3Xpb",
	"l7hkAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
