// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionScopes = "session.Scopes"
)

// Defines values for ActivitySource.
const (
	GoogleCalendar ActivitySource = "google_calendar"
	Manual         ActivitySource = "manual"
	System         ActivitySource = "system"
)

// Valid indicates whether the value is a known member of the ActivitySource enum.
func (e ActivitySource) Valid() bool {
	switch e {
	case GoogleCalendar:
		return true
	case Manual:
		return true
	case System:
		return true
	default:
		return false
	}
}

// Defines values for ActivityType.
const (
	ActivityTypeCommitment ActivityType = "commitment"
	ActivityTypeConference ActivityType = "conference"
	ActivityTypeStay       ActivityType = "stay"
	ActivityTypeTravel     ActivityType = "travel"
	ActivityTypeVacation   ActivityType = "vacation"
)

// Valid indicates whether the value is a known member of the ActivityType enum.
func (e ActivityType) Valid() bool {
	switch e {
	case ActivityTypeCommitment:
		return true
	case ActivityTypeConference:
		return true
	case ActivityTypeStay:
		return true
	case ActivityTypeTravel:
		return true
	case ActivityTypeVacation:
		return true
	default:
		return false
	}
}

// Defines values for CreateActivityRequestType.
const (
	CreateActivityRequestTypeCommitment CreateActivityRequestType = "commitment"
	CreateActivityRequestTypeConference CreateActivityRequestType = "conference"
	CreateActivityRequestTypeStay       CreateActivityRequestType = "stay"
	CreateActivityRequestTypeTravel     CreateActivityRequestType = "travel"
	CreateActivityRequestTypeVacation   CreateActivityRequestType = "vacation"
)

// Valid indicates whether the value is a known member of the CreateActivityRequestType enum.
func (e CreateActivityRequestType) Valid() bool {
	switch e {
	case CreateActivityRequestTypeCommitment:
		return true
	case CreateActivityRequestTypeConference:
		return true
	case CreateActivityRequestTypeStay:
		return true
	case CreateActivityRequestTypeTravel:
		return true
	case CreateActivityRequestTypeVacation:
		return true
	default:
		return false
	}
}

// Activity defines model for Activity.
type Activity struct {
	CreatedAt time.Time          `json:"createdAt"`
	EndDate   openapi_types.Date `json:"endDate"`
	Id        string             `json:"id"`
	Location  *string            `json:"location,omitempty"`
	Notes     *string            `json:"notes,omitempty"`
	Source    ActivitySource     `json:"source"`
	StartDate openapi_types.Date `json:"startDate"`
	Title     string             `json:"title"`
	Type      ActivityType       `json:"type"`
	UserId    string             `json:"userId"`
}

// ActivitySource defines model for Activity.Source.
type ActivitySource string

// ActivityType defines model for Activity.Type.
type ActivityType string

// CreateActivityRequest defines model for CreateActivityRequest.
type CreateActivityRequest struct {
	// EndDate Defaults to startDate if omitted
	EndDate   *openapi_types.Date       `json:"endDate,omitempty"`
	Location  *string                   `json:"location,omitempty"`
	Notes     *string                   `json:"notes,omitempty"`
	StartDate openapi_types.Date        `json:"startDate"`
	Title     string                    `json:"title"`
	Type      CreateActivityRequestType `json:"type"`
}

// CreateActivityRequestType defines model for CreateActivityRequest.Type.
type CreateActivityRequestType string

// DateCheck defines model for DateCheck.
type DateCheck struct {
	Activities []Activity         `json:"activities"`
	Date       openapi_types.Date `json:"date"`

	// HasConflict True if activities on this date span multiple locations
	HasConflict bool `json:"hasConflict"`

	// Location Primary location for the day (Home if no activities)
	Location string `json:"location"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// OkResponse defines model for OkResponse.
type OkResponse struct {
	Ok *string `json:"ok,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListActivitiesParams defines parameters for ListActivities.
type ListActivitiesParams struct {
	// Month Filter by month (YYYY-MM)
	Month *string `form:"month,omitempty" json:"month,omitempty"`

	// From Filter start (YYYY-MM-DD), used with 'to'
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To Filter end (YYYY-MM-DD), used with 'from'
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// CreateActivityJSONRequestBody defines body for CreateActivity for application/json ContentType.
type CreateActivityJSONRequestBody = CreateActivityRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List activities for the authenticated user
	// (GET /api/activities)
	ListActivities(w http.ResponseWriter, r *http.Request, params ListActivitiesParams)
	// Create a new activity
	// (POST /api/activities)
	CreateActivity(w http.ResponseWriter, r *http.Request)
	// Check what activities span a specific date
	// (GET /api/activities/check/{date})
	CheckDate(w http.ResponseWriter, r *http.Request, date openapi_types.Date)
	// Delete an activity by ID
	// (DELETE /api/activities/{id})
	DeleteActivity(w http.ResponseWriter, r *http.Request, id string)
	// Get a single activity by ID
	// (GET /api/activities/{id})
	GetActivity(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List activities for the authenticated user
// (GET /api/activities)
func (_ Unimplemented) ListActivities(w http.ResponseWriter, r *http.Request, params ListActivitiesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new activity
// (POST /api/activities)
func (_ Unimplemented) CreateActivity(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check what activities span a specific date
// (GET /api/activities/check/{date})
func (_ Unimplemented) CheckDate(w http.ResponseWriter, r *http.Request, date openapi_types.Date) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an activity by ID
// (DELETE /api/activities/{id})
func (_ Unimplemented) DeleteActivity(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a single activity by ID
// (GET /api/activities/{id})
func (_ Unimplemented) GetActivity(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListActivities operation middleware
func (siw *ServerInterfaceWrapper) ListActivities(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListActivitiesParams

	// ------------- Optional query parameter "month" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "month", r.URL.Query(), &params.Month, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "month", Err: err})
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListActivities(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateActivity operation middleware
func (siw *ServerInterfaceWrapper) CreateActivity(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateActivity(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckDate operation middleware
func (siw *ServerInterfaceWrapper) CheckDate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", chi.URLParam(r, "date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckDate(w, r, date)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteActivity operation middleware
func (siw *ServerInterfaceWrapper) DeleteActivity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteActivity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetActivity operation middleware
func (siw *ServerInterfaceWrapper) GetActivity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActivity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/activities", wrapper.ListActivities)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/activities", wrapper.CreateActivity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/activities/check/{date}", wrapper.CheckDate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/activities/{id}", wrapper.DeleteActivity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/activities/{id}", wrapper.GetActivity)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYTW/cNhD9KwQbIAkge9eJT3tzvE1qNEkDNz0YjhvQ0mjFWPwIObKhGvrvxVBafVha",
	"r+Mmi+ZkSSRn3sx7M5z1LY+NskaDRs8Xt9yBt0Z7CC+vRHIKXwvwSG+x0Qg6PAprcxkLlEbPvnij6ZuP",
	"M1CCnp44SPmC/zLrTM/qVT/71TnjThsnvKqqiCfgYyctGeMLfqKvRS4T5hrHVcTfG3xtCp3sDsQpeFO4",
	"GJg2yNLgu4r4X1oUmBkn/4EdYnlvkJFf0EgeIOG0pzlO1o9ilNcSS3q2zlhwKGv+Ygd04ChATI1TAvmC",
	"JwJhD6UCHnEsLfAF9+ikXlGMoJOlQBgdmNorQxZGn3NTJ2JyURussY1W6ozTEuhC8cU5V0IXIucRXxmz",
	"yuFzLHLQiXA84r70CIpfTKDyKBw+OAaUmMMknvpDhwaduAZC41GUPCL2U3CgY7J7LZqY6btSEhUJYwpe",
	"4cGdTCWuijhpXjoS1zklt928htmY68fYMdZmMOrx3iEwl18gDuV0HFbXqukV+FA8PSUMBbmEVBQ5eoaG",
	"tUCYTJlREkmf0fa0P1Yjj+NWSf0W9AozvjiIdsT0HTo3EjjFEC0cZxBfjVkRNW3Nm0RQfluHaftDGyoX",
	"zonwnjw0l5nwx0anuYxxrIiPrggC6MAxoxlm0jOyx7wVmqkiR2lzYGvufefn0pgchL6rjKGXD04q4cr2",
	"PEuNY5gBS0TJnv1mVMCgTQ/Gc76Nlybe1mvUz/Aw7Cmmht17XEO0PF3rI1N/XG22Y64eZIQqBOLCSSz/",
	"JPLrwx68bxIqKY+xMVeSgtZCBTFY+3m9p1OIlb9DWd9HUqdmTMdaVszmQmupV0zohMVNtlgCCHFLUxqu",
	"c42sri1wvm1qJB/6xo6b9s6OPpxQoYGrYfP5/sH+nFJkLGhhJV/wl/vz/Zc84lZgFoKcCStnw+JYQZAq",
	"5TFwS12Xv5Uej/oMW+GEAiREi/O7Mb6WOYJjlyVTRmPGnp2dnZ3tvXtHugq5/FqAK7tUhl086l39ViCC",
	"o61/f/qU3B5We/TnRfVkSpkb3Idm0freWy6fR6zwkLAbiRl7iubpBjipM2qAZkuZb0QAOtnsn7xsQoDm",
	"m/xfRMMB9MV8/k2D1n/sh+Phi+TCTL+z0anD+cEmJy382WBa7Jdm0FlblOcXFLUvFPW2tcdeI103ucEI",
	"SOl3hMQaPyHy4Q3P644HHl+ZpPxug+v0GFENGyy6AqoRqQffDUTH5Zi7GmCyTmZZMzffzlzvZ88PJruG",
	"yATTcNPDWUV3+9kspnFgdkt1U21sbmFmaIbBe/tamNjQsGB1UNnrOqbG2pVxU65DXndZ2PdpoJuWJkQQ",
	"Iq3DdOCL/MdTGnzdZGJQxWECEsxbiGUq4zAWTfJ8K5OqvmtzqEezIcXL8L1X2nd4niAv/JLYTN0uqerN",
	"OFNchdiSRzJEhw63H2r/mfBwSmtcjBhczzyXJTtZks/JOnwD+LMydF9D/UjX0KCZ/o9IegNIBSb1KocR",
	"T1VV/RsAAP//NGrPI+kSAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
